SELECT DISTINCT *
  FROM ( --
        SELECT X.MATERIAL_TRANSACTION_ID
               ,X.QTY_PRIMARY_MTRAN
               ,X.QTY_TRANSACTION_MTRAN
               ,COUNT(XS.MSER_SERIAL_NUMBER_ID) OVER(PARTITION BY X.MATERIAL_TRANSACTION_ID) C
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
          LEFT OUTER JOIN MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
            ON X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID
         WHERE X.ITEM_ITEM_ID_FOR =
               (SELECT ITEM_ID
                  FROM MAM.MAM_ITEMS I
                 WHERE I.COD_ITEM = &COD_ITEM)
        --
        )
 WHERE ABS(QTY_TRANSACTION_MTRAN) != C
