SELECT (SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE RXS.ITEM_ITEM_ID = I.ITEM_ID) AS ITEMS
      ,RXS.*
  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
 WHERE 1 = 1
       AND EXISTS (SELECT NULL
          FROM MAM.MAM_ITEMS I
         WHERE I.COD_ITEM IN (&COD_ITEM)
               AND RXS.ITEM_ITEM_ID = I.ITEM_ID)
   FOR UPDATE
