SELECT (SELECT I.COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = S.ITEM_ITEM_ID) AS ITEM
      ,S.SERIAL_NUMBER_ID
      ,S.ITEM_ITEM_ID
      ,S.COD_SERIAL_NUMBER_MSER
      ,S.LKP_STA_CURRENT_MSER
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SERIAL_NUMBERS')
                                                    ,UPPER('LKP_STA_CURRENT_MSER')
                                                    ,S.LKP_STA_CURRENT_MSER) AS LKP_STA_CURRENT_MSER_DES
      ,(SELECT 'USED'
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                 WHERE XS.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID)) AS XS
      ,(SELECT 'USED'
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
                 WHERE RXS.ITEM_ITEM_ID = S.ITEM_ITEM_ID
                       AND RXS.NUM_SERIAL_MRCVS = S.COD_SERIAL_NUMBER_MSER)) AS RXS
      ,S.DAT_DISABLE_MSER
      ,TO_CHAR(S.DAT_DISABLE_MSER
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_DISABLE_MSER_H
      ,S.NAM_SUB_INVENTORY_MSER
      ,S.STA_OLD_MSER
      ,S.COD_REVISION_MSER
  FROM MAM.MAM_SERIAL_NUMBERS S
 WHERE 1 = 1
       AND EXISTS (SELECT NULL
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = S.ITEM_ITEM_ID
               AND I.COD_ITEM = &COD_ITEM)
   FOR UPDATE
