SELECT SX1.MSER_SERIAL_NUMBER_ID AS SERIAL_NUMBER_ID
      ,X1.QTY_PRIMARY_MTRAN
      ,(SELECT COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = X1.ITEM_ITEM_ID_FOR) AS ITEM
      ,(SELECT SN.COD_SERIAL_NUMBER_MSER
          FROM MAM.MAM_SERIAL_NUMBERS SN
         WHERE SN.SERIAL_NUMBER_ID = SX1.MSER_SERIAL_NUMBER_ID) COD_SERIAL_NUMBER
      ,Z.CS
      ,(SELECT TT.NAM_TRANSACTION_TYPE_MTYP
          FROM MAM.MAM_TRANSACTION_TYPES TT
         WHERE TT.TRANSACTION_TYPE_ID = X1.MTYP_TRANSACTION_TYPE_ID) TT
      ,X1.MATERIAL_TRANSACTION_ID
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X1
 INNER JOIN MAM.MAM_TRANSACTION_SERIAL_NUMBERS SX1
    ON X1.MATERIAL_TRANSACTION_ID = SX1.MTRAN_MATERIAL_TRANSACTION_ID
 INNER JOIN (
             --
             SELECT DISTINCT MSER_SERIAL_NUMBER_ID, D.CS
             
               FROM ( --
                      SELECT XS.MSER_SERIAL_NUMBER_ID
                             ,SUM((SELECT SIGN(X.QTY_PRIMARY_MTRAN)
                                    FROM MAM.MAM_MATERIAL_TRANSACTIONS X
                                   WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
                                         X.MATERIAL_TRANSACTION_ID)) OVER(PARTITION BY XS.MSER_SERIAL_NUMBER_ID) AS SS
                             ,COUNT(XS.MTRAN_MATERIAL_TRANSACTION_ID) OVER(PARTITION BY XS.MSER_SERIAL_NUMBER_ID) AS CS
                        FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                      --
                      ) D
              WHERE D.SS != 0
                    AND MOD(D.CS, 2) = 1
             --
             ) Z
    ON SX1.MSER_SERIAL_NUMBER_ID = Z.MSER_SERIAL_NUMBER_ID
 WHERE &COD_ITEM IS NULL
       OR
       X1.ITEM_ITEM_ID_FOR =
       (SELECT ITEM_ID FROM MAM.MAM_ITEMS I WHERE I.COD_ITEM = &COD_ITEM)
 ORDER BY SX1.MSER_SERIAL_NUMBER_ID, X1.DAT_TRANSACTION_MTRAN
