SELECT D.MATERIAL_TRANSACTION_ID AS XID
      ,(SELECT X1.MTYP_TRANSACTION_TYPE_ID
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X1
         WHERE X1.MATERIAL_TRANSACTION_ID = D.MATERIAL_TRANSACTION_ID) XT
      ,D.ITEM_ITEM_ID AS ITEM_ID
      ,D.COD_SERIAL_NUMBER_MSER AS COD_SERIAL_NUMBER
      ,(SELECT S1.SERIAL_NUMBER_ID
          FROM MAM.MAM_SERIAL_NUMBERS S1
         WHERE S1.ITEM_ITEM_ID = D.ITEM_ITEM_ID
               AND S1.COD_SERIAL_NUMBER_MSER = D.COD_SERIAL_NUMBER_MSER) AS SERIAL_NUMBER_ID
      ,(SELECT DISTINCT RX1.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS1
         INNER JOIN MAM.MAM_RCV_TRANSACTIONS RX1
            ON RXS1.MRCV_RCV_TRANSACTION_ID = RX1.RCV_TRANSACTION_ID
         WHERE RX1.MTRAN_MATERIAL_TRANSACTION_ID =
               D.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
      ,(SELECT DISTINCT RX1.LKP_TYP_TRANSACTION_MRCV
          FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS1
         INNER JOIN MAM.MAM_RCV_TRANSACTIONS RX1
            ON RXS1.MRCV_RCV_TRANSACTION_ID = RX1.RCV_TRANSACTION_ID
         WHERE RX1.MTRAN_MATERIAL_TRANSACTION_ID =
               D.MATERIAL_TRANSACTION_ID) AS LKP_TYP_TRANSACTION_MRCV
      ,(SELECT DISTINCT RX1.RCV_TRANSACTION_ID
          FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS1
         INNER JOIN MAM.MAM_RCV_TRANSACTIONS RX1
            ON RXS1.MRCV_RCV_TRANSACTION_ID = RX1.RCV_TRANSACTION_ID
         WHERE RX1.MTRAN_MATERIAL_TRANSACTION_ID =
               D.MATERIAL_TRANSACTION_ID) AS RCV_TRANSACTION_ID
  FROM ( --
        SELECT DISTINCT RX.MTRAN_MATERIAL_TRANSACTION_ID AS MATERIAL_TRANSACTION_ID
                        ,RX.ITEM_ITEM_ID                  AS ITEM_ITEM_ID
                        ,RXS.NUM_SERIAL_MRCVS             AS COD_SERIAL_NUMBER_MSER
          FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
         INNER JOIN MAM.MAM_RCV_TRANSACTIONS RX
            ON RXS.MRCV_RCV_TRANSACTION_ID = RX.RCV_TRANSACTION_ID
         WHERE RX.LKP_TYP_TRANSACTION_MRCV = 'Deliver'
               AND RXS.ITEM_ITEM_ID =
               (SELECT ITEM_ID
                      FROM MAM.MAM_ITEMS I
                     WHERE I.COD_ITEM = &COD_ITEM)
        -----------------------------------------------------------------        
        MINUS -----------------------------------------------------------
        -----------------------------------------------------------------        
        SELECT DISTINCT MATERIAL_TRANSACTION_ID
                        ,ITEM_ITEM_ID_FOR        AS ITEM_ITEM_ID
                        ,COD_SERIAL_NUMBER_MSER  AS COD_SERIAL_NUMBER_MSER
          FROM ( --
                 SELECT X.MATERIAL_TRANSACTION_ID
                        ,X.QTY_PRIMARY_MTRAN
                        ,COUNT(XS.MSER_SERIAL_NUMBER_ID) OVER(PARTITION BY XS.MTRAN_MATERIAL_TRANSACTION_ID) AS CNT
                        ,S.COD_SERIAL_NUMBER_MSER
                        ,X.ITEM_ITEM_ID_FOR
                   FROM MAM.MAM_MATERIAL_TRANSACTIONS X
                   LEFT OUTER JOIN MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                     ON X.MATERIAL_TRANSACTION_ID =
                        XS.MTRAN_MATERIAL_TRANSACTION_ID
                   LEFT OUTER JOIN MAM.MAM_SERIAL_NUMBERS S
                     ON XS.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID
                  WHERE X.ITEM_ITEM_ID_FOR =
                        (SELECT ITEM_ID
                           FROM MAM.MAM_ITEMS I
                          WHERE I.COD_ITEM = &COD_ITEM)
                 --
                 )
         WHERE ABS(QTY_PRIMARY_MTRAN) != ABS(NVL(CNT, 0))
        --
        ) D
