SELECT MSN.SERIAL_NUMBER_ID
  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS MRST
      ,MAM.MAM_SERIAL_NUMBERS          MSN
 WHERE MRST.NUM_SERIAL_MRCVS = MSN.COD_SERIAL_NUMBER_MSER
       AND MRST.ITEM_ITEM_ID = MSN.ITEM_ITEM_ID
       AND MRST.MRCV_RCV_TRANSACTION_ID = 128151
       AND MSN.ITEM_ITEM_ID = 20989
       AND MSN.SERIAL_NUMBER_ID NOT IN
       (SELECT FIXAS.MSER_SERIAL_NUMBER_ID
              FROM FIA.FIA_FIXED_ASSETS FIXAS
             WHERE FIXAS.MSER_SERIAL_NUMBER_ID IS NOT NULL);
