SELECT RX.RCV_TRANSACTION_ID AS RX_ID
      ,RX.QTY_PRIMARY_MRCV AS QTY
      ,SUM(RXS.QTY_MRCVS) OVER(PARTITION BY RX.RCV_TRANSACTION_ID) AS SUM_QTY_OVER_RCV_ID
      ,RXS.NUM_SERIAL_MRCVS AS NUM_SERIAL
      ,RXS.QTY_MRCVS
      ,S.LKP_STA_CURRENT_MSER AS SERIAL_STATUS
      ,SUM(RXS.QTY_MRCVS) OVER(PARTITION BY S.SERIAL_NUMBER_ID) AS SUM_QTY_OVER_SERIAL
      ,RX.NUM_RECEIPT_AP_MRCV AS NUM_RECEIPT
  FROM (SELECT RX1.*
          FROM MAM.MAM_RCV_TRANSACTIONS RX1
         WHERE RX1.LKP_TYP_TRANSACTION_MRCV = 'Deliver') RX
  LEFT OUTER JOIN MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
    ON RX.RCV_TRANSACTION_ID = RXS.MRCV_RCV_TRANSACTION_ID
  LEFT OUTER JOIN MAM.MAM_SERIAL_NUMBERS S
    ON S.ITEM_ITEM_ID = RX.ITEM_ITEM_ID
       AND S.COD_SERIAL_NUMBER_MSER = RXS.NUM_SERIAL_MRCVS
 WHERE RX.ITEM_ITEM_ID =
       (SELECT ITEM_ID FROM MAM.MAM_ITEMS I WHERE I.COD_ITEM = &COD_ITEM)

 ORDER BY --RXS.NUM_SERIAL_MRCVS
          RX.RCV_TRANSACTION_ID
