SELECT I.ITEM_ID
      ,I.COD_ITEM
      ,NVL((SELECT COUNT(1)
             FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
            WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
                  X.MATERIAL_TRANSACTION_ID), 0) AS XS_CNT
      ,COUNT(1) OVER(PARTITION BY I.ITEM_ID) AS CNT
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 INNER JOIN MAM.MAM_ITEMS I
    ON X.ITEM_ITEM_ID_FOR = I.ITEM_ID
 WHERE I.COD_SERIAL_NUMBER_CONTROL_ITEM = 1
       AND NVL((SELECT COUNT(1)
                 FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
                      X.MATERIAL_TRANSACTION_ID), 0) !=
       ABS(X.QTY_PRIMARY_MTRAN)
       AND X.ITEM_ITEM_ID_FOR NOT IN (177512, 177505)
 ORDER BY I.COD_ITEM
