SELECT I.ITEM_ID
      ,I.COD_ITEM
  FROM MAM.MAM_ITEMS I
 WHERE I.COD_SERIAL_NUMBER_CONTROL_ITEM = 1
       AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.ITEM_ITEM_ID = I.ITEM_ID
               AND NOT EXISTS
         (SELECT NULL
                  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
                 WHERE RXS.MRCV_RCV_TRANSACTION_ID = RX.RCV_TRANSACTION_ID))
--
;
SELECT I.ITEM_ID
      ,I.COD_ITEM
  FROM MAM.MAM_ITEMS I
 WHERE I.COD_SERIAL_NUMBER_CONTROL_ITEM = 1
       AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
         WHERE X.ITEM_ITEM_ID_FOR = I.ITEM_ID
               AND NOT EXISTS (SELECT NULL
                  FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                 WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
                       X.MATERIAL_TRANSACTION_ID))
--
;
