--GRANT SELECT ON FND.FND_USERS TO SUP_BACKEND
SELECT '''' || TRIM(U.IDE_USER_USRS) || ''''
      ,CASE
         WHEN U.LKP_USER_TYPE_USRS = 'I' THEN
          'Irisa'
       END AS IRISA
      ,U.*
  FROM FND.FND_USERS U
 WHERE 1 = 1
      AND U.IDE_USER_USRS LIKE UPPER(TRIM('&IDE_USER_USRS'))
--   AND UPPER(FND.FND_REPLACE_STRING(U.NAM_USER_USRS)) LIKE UPPER(FND.FND_REPLACE_STRING('%' || '&NAM_USER_USRS' || '%'))
 ORDER BY U.NAM_USER_USRS
