--GRANT SELECT ON FND.FND_USERS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_HIERARCHIES TO SUP_BACKEND
--GRANT SELECT ON FND.FND_HIERARCHY_DETAILS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_HIERARCHY_FORMS TO SUP_BACKEND
SELECT H.HIERARCHY_ID
      ,REPLACE(H.NAM_HIERARCHY_HIRNM, 'SUBINVENTORY', '') AS SUBINVENTORY
      ,H.NAM_HIERARCHY_HIRNM
      ,F.PROG_NAM_PRG_PROG AS FORM_NAME
      ,(SELECT S.DES_MSINV
          FROM MAM.MAM_SUB_INVENTORIES S
         WHERE S.NAM_SUB_INVENTORY_MSINV =
               SUBSTR(H.NAM_HIERARCHY_HIRNM, -2, 2)) DES_MSINV
  FROM FND.FND_HIERARCHIES H
  LEFT OUTER JOIN FND.FND_HIERARCHY_FORMS F
    ON H.HIERARCHY_ID = F.HIRNM_HIERARCHY_ID
 WHERE 1 = 1
       AND H.APPLS_APPLICATION_SYSTEM_ID = 31
       AND H.NAM_HIERARCHY_HIRNM LIKE UPPER('SUBINVENTORY%')

 ORDER BY 2
         ,1
--
;
SELECT H.NAM_HIERARCHY_HIRNM
      ,F.PROG_NAM_PRG_PROG AS FORM_NAME
      ,(SELECT S.DES_MSINV
          FROM MAM.MAM_SUB_INVENTORIES S
         WHERE S.NAM_SUB_INVENTORY_MSINV =
               SUBSTR(H.NAM_HIERARCHY_HIRNM, -2, 2)) DES_MSINV
      ,D.USRS_IDE_USER_USRS
      ,(SELECT U.NAM_USER_USRS
          FROM FND.FND_USERS U
         WHERE U.IDE_USER_USRS = D.USRS_IDE_USER_USRS) U
      ,D.*
  FROM FND.FND_HIERARCHIES H
  LEFT OUTER JOIN FND.FND_HIERARCHY_DETAILS D
    ON H.HIERARCHY_ID = D.HIRNM_HIERARCHY_ID
  LEFT OUTER JOIN FND.FND_HIERARCHY_FORMS F
    ON H.HIERARCHY_ID = F.HIRNM_HIERARCHY_ID
 WHERE 1 = 1
       AND H.APPLS_APPLICATION_SYSTEM_ID = 31
       AND D.USRS_IDE_USER_USRS = '&IDE_USER_USRS'
       AND H.NAM_HIERARCHY_HIRNM LIKE UPPER('SUBINVENTORY%')
 ORDER BY 1
         ,3
--
;
