PL/SQL Developer Test script 3.0
44
BEGIN
  UPDATE MAM.MAM_SUB_INVENTORIES S
     SET S.LKP_RESPONSIBILITY_RESTRICTED_ = UPPER(TRIM(S.LKP_RESPONSIBILITY_RESTRICTED_));
  :RESULT := APPS.APP_FND_HIERARCHY_DETAILS_PKG.REMOVE_USERLESS;
  :RESULT := APPS.APP_FND_HIERARCHY_DETAILS_PKG.FLATEN_FOR_SUBINVENTORIES;
  :RESULT := APPS.APP_FND_HIERARCHIES_PKG.REMOVE_REDUNDUNTS;
  :RESULT := APPS.APP_FND_HIERARCHY_DETAILS_PKG.ITERATION_OF_REMOVING_REPEATED;
  :RESULT := APPS.APP_FND_HIERARCHY_DETAILS_PKG.ITERATION_OF_REMOVING_REPEATED;
  :RESULT := APPS.APP_FND_HIERARCHY_DETAILS_PKG.ITERATION_OF_REMOVING_REPEATED;
  APPS.APP_FND_HIERARCHIES_PKG.ADJUST_SEQUENCE;
  APPS.APP_FND_HIERARCHY_DETAILS_PKG.ADJUST_SEQUENCE;
  COMMIT;
  FOR C IN ( --
            SELECT H.HIERARCHY_ID
                   ,REPLACE(H.NAM_HIERARCHY_HIRNM, 'SUBINVENTORY', '') AS SUBINVENTORY
                   ,H.NAM_HIERARCHY_HIRNM
                   ,F.PROG_NAM_PRG_PROG AS FORM_NAME
                   ,(SELECT S.DES_MSINV
                       FROM MAM.MAM_SUB_INVENTORIES S
                      WHERE S.NAM_SUB_INVENTORY_MSINV =
                            SUBSTR(H.NAM_HIERARCHY_HIRNM, -2, 2)) DES_MSINV
              FROM FND.FND_HIERARCHIES H
              LEFT OUTER JOIN FND.FND_HIERARCHY_FORMS F
                ON H.HIERARCHY_ID = F.HIRNM_HIERARCHY_ID
             WHERE 1 = 1
                   AND H.APPLS_APPLICATION_SYSTEM_ID = 31
                   AND H.NAM_HIERARCHY_HIRNM LIKE UPPER('SUBINVENTORY%')
                   AND
                   REPLACE(H.NAM_HIERARCHY_HIRNM, 'SUBINVENTORY', '') = :SUBINVENTORY
             ORDER BY 2
                      ,1
            --
            )
  LOOP
    :P_HIERARCHY_DETAIL_ID := NULL;
    :RESULT                := APPS.APP_FND_HIERARCHY_DETAILS_PKG.ADD(P_HIERARCHY_DETAIL_ID => :P_HIERARCHY_DETAIL_ID
                                                                    ,P_HIRNM_HIERARCHY_ID  => C.HIERARCHY_ID
                                                                    ,P_USRS_IDE_USER_USRS  => :P_USRS_IDE_USER_USRS);
    IF :RESULT IS NULL
    THEN
      COMMIT;
    END IF;
  END LOOP;
END;
4
result
0
5
p_hierarchy_detail_id
1
5970
4
SUBINVENTORY
1
﻿10
5
P_USRS_IDE_USER_USRS
1
﻿51132
5
0
