--GRANT SELECT ON FND.FND_GROUPS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_APPLICATION_SYSTEMS TO SUP_BACKEND
SELECT II.IDE_GRP_GROUP
      ,II.APPLS_APPLICATION_SYSTEM_ID
      ,II.DES_GRP_GROUP
      ,II.DAT_CREATE_GROUP
      ,TO_CHAR(II.DAT_CREATE_GROUP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_CREATE_GROUP_H
      ,II.DAT_EXP_GROUP
      ,TO_CHAR(II.DAT_EXP_GROUP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_EXP_GROUP_H
      ,II.FLG_ENABLED_GROUP
      ,II.FLG_CRT_ACSS_GRP_GROUP
      ,II.LKP_GRP_TYPE_GROUP
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('FND_GROUPS')
                                                    ,UPPER('LKP_GRP_TYPE_GROUP')
                                                    ,II.LKP_GRP_TYPE_GROUP) AS LKP_GRP_TYPE_GROUP_DES
      ,II.DES_GRP_LIST_QUERY_GROUP
      ,II.NUM_GRP_LEVEL_GROUP
      ,II.FLG_HAS_DISCOVERER_GROUP
      ,II.DES_LATIN_GRP_GROUP
      ,II.FLG_DEVOLVEABLE_GRP_GROUP
      ,II.FLG_BIPUB_GROUP
      ,II.FLG_ASIGN_DEFAULT_NODE_GROUP
      ,II.LKP_WFM_TYPE_GROUP
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('FND_GROUPS')
                                                    ,UPPER('LKP_WFM_TYPE_GROUP')
                                                    ,II.LKP_WFM_TYPE_GROUP) AS LKP_WFM_TYPE_GROUP_DES
      ,II.FLG_APEX_GROUP
      ,II.FLG_ASSIGN_TO_SUB_GROUP
      ,II.GROUP_IDE_GRP_GROUP_P
  FROM FND.FND_GROUPS II

  LEFT OUTER JOIN FND.FND_APPLICATION_SYSTEMS A1
    ON II.APPLS_APPLICATION_SYSTEM_ID = A1.APPLICATION_SYSTEM_ID
  LEFT OUTER JOIN FND.FND_GROUPS A2
    ON II.GROUP_IDE_GRP_GROUP_P = A2.IDE_GRP_GROUP

 WHERE UPPER(TRIM(II.IDE_GRP_GROUP)) LIKE UPPER(TRIM('mam%'))
 ORDER BY II.IDE_GRP_GROUP
