--GRANT SELECT ON FND.FND_MENU_NODES TO SUP_BACKEND
--GRANT SELECT ON FND.FND_SETUPS TO SUP_BACKEND
WITH A AS
 ( --
  SELECT DS.NAM_PROJECT_SETUP AS PROJECT_NAME
         ,DS.COD_PROJECT_SETUP AS PROJECT_COD
         ,N.NAM_NOD_MNOD AS NODE
         ,N.MNOD_NAM_NOD_MNOD AS FATHER
         ,N.PROG_NAM_PRG_PROG AS RELATED_FORM
         ,CASE
            WHEN N.PROG_NAM_PRG_PROG LIKE UPPER(TRIM('%&RELATED_FROM_LIKE%')) THEN
             'This One!'
          END AS THE_ONE
         ,N.DES_NOD_MNOD AS CAPTION
    FROM FND.FND_MENU_NODES N
   CROSS JOIN --
   (SELECT S.NAM_PROJECT_SETUP
          ,S.COD_PROJECT_SETUP
      FROM FND.FND_SETUPS S) DS
  
   WHERE (N.NAM_NOD_MNOD LIKE UPPER('pur%'))
   START WITH N.MNOD_NAM_NOD_MNOD = UPPER('IS')
  CONNECT BY PRIOR NAM_NOD_MNOD = MNOD_NAM_NOD_MNOD
  --
  )
SELECT PROJECT_NAME
      ,PROJECT_COD
      ,NODE
      ,FATHER
      ,RELATED_FORM
      ,NULL AS THE_ONE
      ,CAPTION
  FROM A
UNION
SELECT PROJECT_NAME
      ,PROJECT_COD
      ,NODE
      ,FATHER
      ,RELATED_FORM
      ,THE_ONE
      ,CAPTION
  FROM A
 WHERE THE_ONE IS NOT NULL
UNION
SELECT NULL AS PROJECT_NAME
      ,NULL AS PROJECT_COD
      ,NULL AS NODE
      ,NULL AS FATHER
      ,NULL AS RELATED_FORM
      ,'XXXXXXXXXX' AS THE_ONE
      ,NULL AS CAPTION
  FROM A
 WHERE THE_ONE IS NOT NULL
 ORDER BY THE_ONE
         ,NODE;
WITH A AS
 ( --
  SELECT DS.NAM_PROJECT_SETUP AS PROJECT_NAME
         ,DS.COD_PROJECT_SETUP AS PROJECT_COD
         ,N.NAM_NOD_MNOD AS NODE
         ,N.MNOD_NAM_NOD_MNOD AS FATHER
         ,N.PROG_NAM_PRG_PROG AS RELATED_FORM
         ,CASE
            WHEN N.PROG_NAM_PRG_PROG LIKE UPPER(TRIM('%&RELATED_FROM_LIKE%')) THEN
             'This One!'
          END AS THE_ONE
         ,N.DES_NOD_MNOD AS CAPTION
    FROM FND.FND_MENU_NODES N
   CROSS JOIN --
   (SELECT S.NAM_PROJECT_SETUP
          ,S.COD_PROJECT_SETUP
      FROM FND.FND_SETUPS S) DS
  
   WHERE (N.NAM_NOD_MNOD LIKE UPPER('mam%'))
   START WITH N.MNOD_NAM_NOD_MNOD = UPPER('IS')
  CONNECT BY PRIOR NAM_NOD_MNOD = MNOD_NAM_NOD_MNOD
  --
  )
SELECT PROJECT_NAME
      ,PROJECT_COD
      ,NODE
      ,FATHER
      ,RELATED_FORM
      ,NULL AS THE_ONE
      ,CAPTION
  FROM A
UNION
SELECT PROJECT_NAME
      ,PROJECT_COD
      ,NODE
      ,FATHER
      ,RELATED_FORM
      ,THE_ONE
      ,CAPTION
  FROM A
 WHERE THE_ONE IS NOT NULL
UNION
SELECT NULL AS PROJECT_NAME
      ,NULL AS PROJECT_COD
      ,NULL AS NODE
      ,NULL AS FATHER
      ,NULL AS RELATED_FORM
      ,'XXXXXXXXXX' AS THE_ONE
      ,NULL AS CAPTION
  FROM A
 WHERE THE_ONE IS NOT NULL
 ORDER BY THE_ONE
         ,NODE
