--GRANT SELECT ON FND.FND_GROUPS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_GROUP_USERS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_USERS TO SUP_BACKEND

SELECT G.IDE_GRP_GROUP
      ,G.DES_GRP_GROUP
      ,U.NAM_USER_USRS
      ,GU.*
  FROM FND.FND_GROUPS G
  LEFT OUTER JOIN FND.FND_GROUP_USERS GU
    ON G.IDE_GRP_GROUP = GU.GROUP_IDE_GRP_GROUP
 INNER JOIN FND.FND_USERS U
    ON GU.USRS_IDE_USER_USRS = U.IDE_USER_USRS
 WHERE 1 = 0
       OR UPPER(TRIM(G.IDE_GRP_GROUP)) LIKE UPPER(TRIM('%&ide_grp_group%'))
--OR UPPER(TRIM(GU.USRS_IDE_USER_USRS)) = UPPER(TRIM('&usrs_ide_user_usrs'))
--OR UPPER(TRIM('&ide_grp_group')) IS NULL
--OR UPPER(TRIM('&usrs_ide_user_usrs')) IS NULL
 ORDER BY GU.USRS_IDE_USER_USRS
         ,G.IDE_GRP_GROUP
