--GRANT SELECT ON FND.FND_MENU_NODE_GROUPS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_MENU_NODES TO SUP_BACKEND
--GRANT SELECT ON FND.FND_GROUPS TO SUP_BACKEND
SELECT N.PROG_NAM_PRG_PROG
      ,(SELECT P.NAM_TITLE_PROG
          FROM FND.FND_PROGRAMS P
         WHERE P.NAM_PRG_PROG = N.PROG_NAM_PRG_PROG) AS NAM_TITLE_PROG
      ,NG.GROUP_IDE_GRP_GROUP
      ,G.DES_GRP_GROUP
      ,U.IDE_USER_USRS
      ,U.NAM_USER_USRS
  FROM FND.FND_MENU_NODE_GROUPS NG
 INNER JOIN FND.FND_MENU_NODES N
    ON NG.MNOD_NAM_NOD_MNOD = N.NAM_NOD_MNOD
 INNER JOIN FND.FND_GROUPS G
    ON NG.GROUP_IDE_GRP_GROUP = G.IDE_GRP_GROUP
 INNER JOIN FND.FND_GROUP_USERS GU
    ON G.IDE_GRP_GROUP = GU.GROUP_IDE_GRP_GROUP
 INNER JOIN FND.FND_USERS U
    ON GU.USRS_IDE_USER_USRS = U.IDE_USER_USRS

 WHERE 1 = 1
   AND NG.GROUP_IDE_GRP_GROUP NOT IN ('MAM_ADMIN')
      --AND NG.MNOD_NAM_NOD_MNOD LIKE UPPER('&SYS%')
   AND (N.PROG_NAM_PRG_PROG LIKE UPPER('%&NAM_PRG_PROG%') OR
       '&NAM_PRG_PROG' = '')
--   AND (G.IDE_GRP_GROUP = '&ide_grp_group' OR '&ide_grp_group' is null)
