--GRANT SELECT ON FND.FND_APPLICATION_SYSTEMS TO SUP_BACKEND
--select * from fnd.fnd_sys_info_viw
SELECT A.NAM_APP_SHORT_APPLS
      ,A.DES_FARSI_APPLS
      ,T.TABLE_NAME
  FROM FND.FND_APPLICATION_SYSTEMS A
  LEFT OUTER JOIN ALL_TABLES T
    ON UPPER(TRIM(A.NAM_APP_SHORT_APPLS)) = UPPER(TRIM(T.OWNER))
 WHERE T.TABLE_NAME LIKE UPPER('&TABLE_NAME')
-- T.TABLE_NAME LIKE UPPER('&TABLE_NAME') || '%'
