--GRANT SELECT ON FND.FND_MENU_NODES TO SUP_BACKEND
SELECT N.PROG_NAM_PRG_PROG
      ,N.NAM_NOD_MNOD
      ,N.DES_NOD_MNOD
      ,N.MNOD_NAM_NOD_MNOD
      ,(SELECT N1.DES_NOD_MNOD
          FROM FND.FND_MENU_NODES N1
         WHERE N1.NAM_NOD_MNOD = N.MNOD_NAM_NOD_MNOD) AS DES_NOD_MNOD_PARENT
  FROM FND.FND_MENU_NODES N
 WHERE N.NAM_NOD_MNOD LIKE 'MAM%'
   AND UPPER(N.PROG_NAM_PRG_PROG) LIKE UPPER('%&PROG_NAM_PRG_PROG%')
