--GRANT SELECT ON FND.FND_REPORTS TO SUP_BACKEND
--GRANT SELECT ON APPS.FND_REPORT_PARAMETERS_VIW TO SUP_BACKEND
SELECT R.NAM_REP_TITLE_REPRT
      ,V.*
  FROM FND.FND_REPORTS R
 INNER JOIN APPS.FND_REPORT_PARAMETERS_VIW V
    ON R.NAM_REP_REPRT = V.REPRT_NAM_REP_REPRT
 WHERE UPPER(R.NAM_REP_REPRT) = UPPER(TRIM('&reprt_nam_rep_reprt'))
 ORDER BY V.NUM_PAR_ORDER_RPAR
