--GRANT ALL ON FND.FND_ERRMSGS TO SUP_BACKEND
SELECT T.NAM_ERR_CATEGORY_ERMSG
      ,T.COD_ERROR_ERMSG
      ,T.TXT_FERROR_ERMSG
      ,T.TXT_LERROR_ERMSG
  FROM FND.FND_ERRMSGS T
 WHERE T.NAM_ERR_CATEGORY_ERMSG =
       'MAM'AND (T.COD_ERROR_ERMSG = &COD_ERROR_ERMSG
              OR &COD_ERROR_ERMSG IS NULL)
 ORDER BY T.NAM_ERR_CATEGORY_ERMSG
         ,T.COD_ERROR_ERMSG
   FOR UPDATE
