--GRANT SELECT ON FND.FND_GROUP_USERS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_GROUPS TO SUP_BACKEND
--GRANT SELECT ON FND.FND_USERS TO SUP_BACKEND
SELECT II.USRS_IDE_USER_USRS
      ,A3.NAM_USER_USRS
      ,II.GROUP_IDE_GRP_GROUP
      ,A1.DES_GRP_GROUP
      ,II.USRS_IDE_USER_USRS_DEVELOPED
      ,II.FLG_ENABALE_IMPRV_GRPUS
      ,II.LKP_ENABALE_IMPRV_GRPUS
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('FND_GROUP_USERS'), UPPER('LKP_ENABALE_IMPRV_GRPUS'), II.LKP_ENABALE_IMPRV_GRPUS) AS LKP_ENABALE_IMPRV_GRPUS_DES
      ,II.FLG_ENABLED_USER_GRPUS
      ,II.FLG_DEVOLVEABLE_USER_GRPUS
      ,II.NUM_CND_ACCESS_GRPUS
      ,II.DES_ACCESS_TYPE_GRPUS
      ,II.FLG_ENABLE_GRP_USR_GRPUS
      ,II.TXT_DISABLE_REASON_GRPUS
      ,II.FLG_ACCESS_TYPE
  FROM FND.FND_GROUP_USERS II
  LEFT OUTER JOIN FND.FND_GROUPS A1
    ON II.GROUP_IDE_GRP_GROUP = A1.IDE_GRP_GROUP
  LEFT OUTER JOIN FND.FND_USERS A3
    ON II.USRS_IDE_USER_USRS = A3.IDE_USER_USRS
  LEFT OUTER JOIN FND.FND_USERS A2
    ON II.USRS_IDE_USER_USRS_DEVELOPED = A2.IDE_USER_USRS
 WHERE 1 = 1
       AND II.GROUP_IDE_GRP_GROUP LIKE UPPER('MAM%')
       AND II.USRS_IDE_USER_USRS --
       LIKE UPPER(TRIM('&IDE_USER_USRS'))
--  IN (UPPER(TRIM(&IDE_USER_USRS)))
 ORDER BY 1
