--GRANT SELECT ON FND.FND_GROUP_REPORTS_VIW TO SUP_BACKEND
--GRANT SELECT ON FND.FND_GROUP_REPORTS TO SUP_BACKEND
SELECT V.GROUP_IDE_GRP_GROUP
      ,V.*
  FROM --FND.FND_GROUP_REPORTS_VIW 
        FND.FND_GROUP_REPORTS
       --
         V
 WHERE 1 = 1
       AND UPPER(TRIM(V.REPRT_NAM_REP_REPRT)) LIKE UPPER(TRIM('&NAM_REP_REPRT'))
--       AND UPPER(TRIM(V.NAM_REP_REPRT)) LIKE UPPER(TRIM('&NAM_REP_REPRT'))
--       AND UPPER(TRIM(V.NAM_REP_REPRT)) LIKE       '%' || UPPER(TRIM('&NAM_REP_REPRT')) || '%'
