-------nilchi
SELECT XL.MLOT_LOT_NUMBER_ID
      ,SUM(XL.QTY_PRIMARY_MTLOT) OVER(PARTITION BY XL.MLOT_LOT_NUMBER_ID) AS SQ_L
      ,XL.MTRAN_MATERIAL_TRANSACTION_ID
      ,XL.QTY_TRANSACTION_MTLOT
      ,XL.QTY_PRIMARY_MTLOT
      ,XL.DAT_TRANSACTION_MTLOT
      ,XL.*
  FROM MAM.MAM_TRANSACTION_LOT_NUMBERS
       --  JRN.MAM_TRANSACTION_LOT_NUMBER_JRN
       --
        XL
 WHERE 1 = 1
      --   AND XL.MTRAN_MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID) 
   AND (EXISTS (SELECT NULL
                  FROM MAM.MAM_LOT_NUMBERS L
                 INNER JOIN MAM.MAM_ITEMS I
                    ON L.ITEM_ITEM_ID = I.ITEM_ID
                 WHERE XL.MLOT_LOT_NUMBER_ID = L.LOT_NUMBER_ID
                   AND I.COD_ITEM IN (&COD_ITEM)) OR '&COD_ITEM' = '')
-- FOR UPDATE
