SELECT XL.MLOT_LOT_NUMBER_ID
      ,XL.MTRAN_MATERIAL_TRANSACTION_ID
      ,XL.QTY_TRANSACTION_MTLOT
      ,XL.QTY_PRIMARY_MTLOT
--      ,XL.*
  FROM MAM.MAM_TRANSACTION_LOT_NUMBERS XL
 WHERE 1 = 1
       AND XL.MTRAN_MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
   FOR UPDATE
