SELECT (SELECT H.NUM_REQUEST_MREQH
          FROM MAM.MAM_REQUEST_LINES L
         INNER JOIN MAM.MAM_REQUEST_HEADERS H
            ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
         WHERE L.REQUEST_LINE_ID = RSN.MREQL_REQUEST_LINE_ID) AS NUM_REQUEST_MREQH
      ,(SELECT L.LKP_STA_LINE_MREQL
          FROM MAM.MAM_REQUEST_LINES L
         WHERE L.REQUEST_LINE_ID = RSN.MREQL_REQUEST_LINE_ID) AS NUM_REQUEST_MREQH
       
      ,APPS.MAM_SERIAL_NUMBERS_CTRL_PKG.GET_DESCRIPTION(RSN.MSER_SERIAL_NUMBER_ID) AS SERIAL
      ,(SELECT APPS.MAM_ITEMS_CTRL_PKG.GET_DESCRIPTION(P_ITEM_ID => L.ITEM_ITEM_ID)
          FROM MAM.MAM_REQUEST_LINES L
         WHERE L.REQUEST_LINE_ID = RSN.MREQL_REQUEST_LINE_ID) AS ITEM
      ,(SELECT S.LKP_STA_CURRENT_MSER || ': ' ||
               APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SERIAL_NUMBERS')
                                                            ,UPPER('LKP_STA_CURRENT_MSER')
                                                            ,S.LKP_STA_CURRENT_MSER) AS LKP_COD_SYSTEM_MRTRA_DES
        
          FROM MAM.MAM_SERIAL_NUMBERS S
         WHERE S.SERIAL_NUMBER_ID = RSN.MSER_SERIAL_NUMBER_ID) AS LKP_STA_CURRENT_MSER
       
      ,RSN.*
  FROM MAM.MAM_REQUEST_SERIAL_NUMBERS RSN
 WHERE 1 = 1
   AND ('&NUM_REQUEST_MREQH' IS NULL OR EXISTS
        (SELECT NULL
           FROM MAM.MAM_REQUEST_LINES L
          INNER JOIN MAM.MAM_REQUEST_HEADERS H
             ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
          WHERE L.REQUEST_LINE_ID = RSN.MREQL_REQUEST_LINE_ID
            AND H.NUM_REQUEST_MREQH LIKE '&NUM_REQUEST_MREQH'))
/*
       AND ('&SERIAL_NUMBER_ID' IS NULL OR
       RSN.MSER_SERIAL_NUMBER_ID = '&SERIAL_NUMBER_ID')
*/
