SELECT II.REQUEST_TRANSACTION_ID
      ,II.DAT_TRANSACTION_MRTRA
      ,TO_CHAR(II.DAT_TRANSACTION_MRTRA
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_TRANSACTION_MRTRA_H
      ,II.LKP_COD_SYSTEM_MRTRA
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REQUEST_TRANSACTIONS')
                                                    ,UPPER('LKP_COD_SYSTEM_MRTRA')
                                                    ,II.LKP_COD_SYSTEM_MRTRA) AS LKP_COD_SYSTEM_MRTRA_DES
      ,II.MREQL_REQUEST_LINE_ID
      ,(SELECT H.NUM_REQUEST_MREQH
          FROM MAM.MAM_REQUEST_LINES L
         INNER JOIN MAM.MAM_REQUEST_HEADERS H
            ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
         WHERE L.REQUEST_LINE_ID = II.MREQL_REQUEST_LINE_ID) AS NUM_REQUEST_MREQH
      ,II.QTY_TRANSACTION_MRTRA
      ,II.TXT_COMMENT_MRTRA
      ,II.LKP_STATUES_MRTRA
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REQUEST_TRANSACTIONS')
                                                    ,UPPER('LKP_STATUES_MRTRA')
                                                    ,II.LKP_STATUES_MRTRA) AS LKP_STATUES_MRTRA_DES
      ,II.*
  FROM MAM.MAM_REQUEST_TRANSACTIONS II
 WHERE 1 = 1
       AND (&NUM_REQUEST_MREQH IS NULL OR EXISTS
        (SELECT NULL
               FROM MAM.MAM_REQUEST_LINES L
              INNER JOIN MAM.MAM_REQUEST_HEADERS H
                 ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
              WHERE L.REQUEST_LINE_ID = II.MREQL_REQUEST_LINE_ID
                    AND H.NUM_REQUEST_MREQH = &NUM_REQUEST_MREQH))
