SELECT (SELECT DISTINCT T.XID_
          FROM TMPX T
         WHERE T.XID_ = X.MATERIAL_TRANSACTION_ID
               OR T.XID_BACK = X.MATERIAL_TRANSACTION_ID) AS BASE_XID
      ,X.MATERIAL_TRANSACTION_ID AS XID
      ,(SELECT DISTINCT RX.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID =
               (SELECT DISTINCT T.XID_
                  FROM TMPX T
                 WHERE T.XID_ = X.MATERIAL_TRANSACTION_ID
                       OR T.XID_BACK = X.MATERIAL_TRANSACTION_ID) --X.MATERIAL_TRANSACTION_ID
        ) AS NUM_RECEIPT_AP_MRCV
      ,X.QTY_PRIMARY_MTRAN AS QTY
      ,X.MTYP_TRANSACTION_TYPE_ID AS TT
      ,X.ITEM_ITEM_ID_FOR
      ,X.DAT_TRANSACTION_MTRAN
      ,X.TXT_COMM_MTRAN
      ,X.*
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 WHERE EXISTS ( --
        SELECT NULL
          FROM TMPX T
         WHERE T.XID_ = X.MATERIAL_TRANSACTION_ID
               OR T.XID_BACK = X.MATERIAL_TRANSACTION_ID
        --
        )
 ORDER BY 1
         ,X.DAT_TRANSACTION_MTRAN
