SELECT X.TXT_COMM_MTRAN
      ,X.QTY_PRIMARY_MTRAN
      ,X.MATERIAL_TRANSACTION_ID
      ,(SELECT RX.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
      ,TO_CHAR(X.DAT_TRANSACTION_MTRAN
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS D
      ,X.*
  FROM --
        MAM.MAM_MATERIAL_TRANSACTIONS
       --        JRN.MAM_MATERIAL_TRANSACTIONS_JRN
       --
         X
 WHERE X.MATERIAL_TRANSACTION_ID IN
       ( --
        SELECT TO_NUMBER(REPLACE(X1.TXT_COMM_MTRAN
                                 ,'Based on material_transaction_id ='
                                 ,''))
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X1
         WHERE X1.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
        UNION
        SELECT X2.MATERIAL_TRANSACTION_ID
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
         WHERE X2.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
        --
        )
       OR X.TXT_COMM_MTRAN IN
       ( -- 
           SELECT X3.TXT_COMM_MTRAN
             FROM MAM.MAM_MATERIAL_TRANSACTIONS X3
            WHERE X3.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
           --
           )
 ORDER BY TRUNC(X.DAT_TRANSACTION_MTRAN)
         ,ABS(X.QTY_PRIMARY_MTRAN)
         ,X.MATERIAL_TRANSACTION_ID
--         ,X.JRN_ID
