SELECT X.MATERIAL_TRANSACTION_ID AS XID
      ,(SELECT RX.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
      ,X.QTY_PRIMARY_MTRAN AS QTY
      ,X.MTYP_TRANSACTION_TYPE_ID AS TT
      ,X.ITEM_ITEM_ID_FOR
      ,X.DAT_TRANSACTION_MTRAN
      ,X.TXT_COMM_MTRAN
      ,X.*
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 WHERE --
 1 = 1
 AND X.ITEM_ITEM_ID_FOR IN (42 --, 119027
                            )
 AND X.MTYP_TRANSACTION_TYPE_ID IN (41, 42)
 AND
 TO_CHAR(X.DAT_TRANSACTION_MTRAN, 'YYYY', 'NLS_CALENDAR=PERSIAN') = '1401'
 AND NOT EXISTS
 (SELECT NULL
    FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
   WHERE X2.TXT_COMM_MTRAN LIKE
         '%Based on material_transaction_id = ' || X.MATERIAL_TRANSACTION_ID || '%')
