SELECT L.LOG_ID
      ,L.NAM_CALLER_ROUTINE_CSMLG
      ,L.TXT_PARAMETERS_CSMLG
      ,L.LAST_CHANGE_TS
      ,L.MODULE_NAME
      ,L.OS_USERNAME
      ,L.NAM_SESSION_CSMLG
      ,L.NAM_MAC_CSMLG
      ,L.NAM_IP_CSMLG
      ,L.NAM_COMPUTER_NAME_CSMLG
      ,L.CREATE_DATE
      ,L.CREATE_BY_DB_USER
      ,L.CREATE_BY_APP_USER
  FROM CSM.CSM_LOGS L
 WHERE 1 = 1
      --   AND L.LOG_ID IN (&LOG_ID)
   AND L.CREATE_DATE > TRUNC(SYSDATE)
 ORDER BY L.LOG_ID DESC
--
;
SELECT L.LOG_ID
      ,LR.LOG_RESPONSE_ID
      ,L.NAM_CALLER_ROUTINE_CSMLG
      ,L.TXT_PARAMETERS_CSMLG
      ,L.LAST_CHANGE_TS
      ,L.MODULE_NAME
      ,L.OS_USERNAME
      ,L.NAM_SESSION_CSMLG
      ,L.NAM_MAC_CSMLG
      ,L.NAM_IP_CSMLG
      ,L.NAM_COMPUTER_NAME_CSMLG
      ,L.CREATE_DATE
      ,L.CREATE_BY_DB_USER
      ,L.CREATE_BY_APP_USER
      ,LR.TXT_RESPONSE_CSMLR
  FROM CSM.CSM_LOGS L
 INNER JOIN CSM.CSM_LOG_RESPONSES LR
    ON L.LOG_ID = LR.CSMLG_LOG_ID_CSMLR
 WHERE 1 = 1
      --   AND L.LOG_ID IN (&LOG_ID)
   AND L.CREATE_DATE > TRUNC(SYSDATE)
 ORDER BY L.LOG_ID DESC, LR.LOG_RESPONSE_ID DESC
--
;
