SELECT H.HIERARCHY_ID
--      ,H.APPLS_APPLICATION_SYSTEM_ID
      ,CASE
         WHEN EXISTS ( --
               SELECT NULL
                 FROM FND.FND_HIERARCHY_DETAILS D
                WHERE D.HIRNM_HIERARCHY_ID = H.HIERARCHY_ID
                      AND D.USRS_IDE_USER_USRS = TRIM(&IDE_USER_USRS)) THEN
          1
       END AS EXISTS_
      ,H.NAM_HIERARCHY_HIRNM
      ,H.NAM_LHIERARCHY_HIRNM
      ,H.DES_HIERARCHY_HIRNM
--      ,H.LKP_EMP_OR_BUSU_HIRNM
/*      
      ,H.LKP_EMP_OR_BUSU_HIRNM || CASE
         WHEN H.LKP_EMP_OR_BUSU_HIRNM IS NOT NULL THEN
          ': '
       END ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('FND_HIERARCHIES')
                                                    ,UPPER('LKP_EMP_OR_BUSU_HIRNM')
                                                    ,H.LKP_EMP_OR_BUSU_HIRNM) AS LKP_EMP_OR_BUSU_HIRNM_DES
*/
--      ,H.FLG_CHECK_USR_TYPE_HIRNM
  FROM FND.FND_HIERARCHIES H
 WHERE H.NAM_HIERARCHY_HIRNM LIKE 'SUBINVENTORY%'
 ORDER BY H.NAM_HIERARCHY_HIRNM
