SELECT I.ITEM_ID
      ,I.COD_ITEM
      ,X.MSINV_NAM_SUB_INVENTORY_MSIFOR
      ,X.MSLOC_SUB_INVENTORY_LOCATORFOR
      ,SUM(X.QTY_PRIMARY_MTRAN) AS SQ
      ,(SELECT Q.QTY_MONH
          FROM MAM.MAM_ONHAND_QUANTITIES Q
         WHERE Q.ITEM_ITEM_ID = I.ITEM_ID
               AND Q.MSINV_NAM_SUB_INVENTORY_MSINV =
               X.MSINV_NAM_SUB_INVENTORY_MSIFOR
               AND Q.MSLOC_SUB_INVENTORY_LOCATOR_ID =
               X.MSLOC_SUB_INVENTORY_LOCATORFOR) AS QTY_MONH

  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 INNER JOIN MAM.MAM_ITEMS I
    ON X.ITEM_ITEM_ID_FOR = I.ITEM_ID
 WHERE I.COD_ITEM = TRIM(&COD_ITEM)
 GROUP BY I.ITEM_ID
         ,I.COD_ITEM
         ,X.MSINV_NAM_SUB_INVENTORY_MSIFOR
         ,X.MSLOC_SUB_INVENTORY_LOCATORFOR
