SELECT T.DYN_PROPERTY_NAME_ID
      ,T.NAM_PROPERTY_MDPRN
      ,T.NAM_PROPERTY_EN_MDPRN
      ,T.CREATE_DATE
      ,T.CREATE_BY_DB_USER
      ,T.CREATE_BY_APP_USER
      ,T.LAST_UPDATE_DATE
      ,T.LAST_UPDATE_BY_DB_USER
      ,T.LAST_UPDATE_BY_APP_USER
      ,T.ATTACH_ID
      ,T.LAST_CHANGE_TS
      ,T.MODULE_NAME
      ,T.OS_USERNAME
  FROM MAM.MAM_DYN_PROPERTY_NAMES T
 WHERE 1 = 1
--    AND T.DYN_PROPERTY_NAME_ID IN (&DYN_PROPERTY_NAME_ID)
 ORDER BY T.DYN_PROPERTY_NAME_ID
