SELECT (SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
            ON I.ITEM_ID = X.ITEM_ITEM_ID_FOR
         WHERE X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID) AS ITEMS
      ,(SELECT X.MTYP_TRANSACTION_TYPE_ID
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
         WHERE X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID) AS TT
      ,APPS.MAM_SERIAL_NUMBERS_CTRL_PKG.GET_DESCRIPTION(P_SERIAL_NUMBER_ID => XS.MSER_SERIAL_NUMBER_ID) AS SERIAL
      ,(SELECT F.NUM_ASSET_FIXAS
          FROM FIA.FIA_FIXED_ASSETS F
         WHERE F.MSER_SERIAL_NUMBER_ID = XS.MSER_SERIAL_NUMBER_ID) AS NUM_ASSET_FIXAS
      ,XS.*
  FROM --DELETE   --
       MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
 WHERE 1 = 1
      /*
             AND EXISTS
       (SELECT NULL
                FROM MAM.MAM_ITEMS I
               INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
                  ON I.ITEM_ID = X.ITEM_ITEM_ID_FOR
               WHERE I.COD_ITEM IN (&COD_ITEM)
                     AND
                     X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID)
      */
      --   AND XS.MTRAN_MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
   AND ( --
        XS.MTRAN_MATERIAL_TRANSACTION_ID IN
        ( --
         SELECT MATERIAL_TRANSACTION_ID
           FROM MAM.MAM_MATERIAL_TRANSACTIONS X0
          WHERE X0.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
         UNION
         SELECT X2.ID_TRANSFER_MTRAN
           FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
          WHERE X2.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
         UNION
         SELECT RR.MTRAN_XID_MRTRN
           FROM MAM.MAM_RELATED_TRANSACTIONS RR
          WHERE RR.MTRAN_XID_MRTRN IN (&MATERIAL_TRANSACTION_ID)
             OR RR.MTRAN_XID2_MRTRN IN (&MATERIAL_TRANSACTION_ID)
         UNION
         SELECT RR.MTRAN_XID2_MRTRN
           FROM MAM.MAM_RELATED_TRANSACTIONS RR
          WHERE RR.MTRAN_XID_MRTRN IN (&MATERIAL_TRANSACTION_ID)
             OR RR.MTRAN_XID2_MRTRN IN (&MATERIAL_TRANSACTION_ID)
         --
         ) --
        OR XS.MTRAN_MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
       --
       )
--   AND XS.MSER_SERIAL_NUMBER_ID IN (&SERIAL_NUMBER_ID)
/*
   AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
               RX.MTRAN_MATERIAL_TRANSACTION_ID
           AND RX.NUM_RECEIPT_AP_MRCV IN (&NUM_RECEIPT_AP_MRCV))
*/
--   FOR UPDATE
