SELECT *
  FROM MAM_RCV_SECURITIES RS
 WHERE 1 = 1
   AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RS.MRCV_RCV_ID_MRSEC = RX.RCV_TRANSACTION_ID
           AND RX.NUM_RECEIPT_AP_MRCV IN (&NUM_RECEIPT_AP_MRCV))
--
   FOR UPDATE
