SELECT L.SUB_INVENTORY_LOCATOR_ID
      ,L.MSINV_NAM_SUB_INVENTORY_MSINV
      ,L.COD_LOCATOR_MSLOC
      ,L.FLG_PRIMARY_LOCATOR_MSLOC
      ,L.COD_PICKING_ORDER_MSLOC
      ,L.NUM_LENGTH_MSLOC
      ,L.NUM_WIDTH_MSLOC
      ,L.HEIGHT_MSLOC
      ,L.LKP_LOCATOR_STATUS_MSLOC
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SUB_INVENTORY_LOCATORS')
                                                    ,UPPER('LKP_LOCATOR_STATUS_MSLOC')
                                                    ,L.LKP_LOCATOR_STATUS_MSLOC) AS LKP_LOCATOR_STATUS_MSLOC_DES
      ,L.FLG_AVAILABILITY_PUSH_MSLOC
      ,L.FLG_AVAILABILITY_PUT_MSLOC
      ,L.FLG_ENABLED_MSLOC
      ,L.CREATE_DATE
      ,L.CREATE_BY_DB_USER
      ,L.CREATE_BY_APP_USER
      ,L.LAST_UPDATE_DATE
      ,L.LAST_UPDATE_BY_DB_USER
      ,L.LAST_UPDATE_BY_APP_USER
      ,L.ATTACH_ID
  FROM MAM.MAM_SUB_INVENTORY_LOCATORS L
 WHERE 1 = 1
      --       AND L.SUB_INVENTORY_LOCATOR_ID = &SUB_INVENTORY_LOCATOR_ID
   AND L.MSINV_NAM_SUB_INVENTORY_MSINV IN (&NAM_SUB_INVENTORY)
 ORDER BY L.MSINV_NAM_SUB_INVENTORY_MSINV, L.COD_LOCATOR_MSLOC
--   FOR UPDATE
