SELECT (SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
            ON I.ITEM_ID = X.ITEM_ITEM_ID_FOR
         WHERE X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID) AS ITEMS
      ,XS.*
  FROM --DELETE   --
       MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
 WHERE 1 = 1
      /*
             AND EXISTS
       (SELECT NULL
                FROM MAM.MAM_ITEMS I
               INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
                  ON I.ITEM_ID = X.ITEM_ITEM_ID_FOR
               WHERE I.COD_ITEM IN (&COD_ITEM)
                     AND
                     X.MATERIAL_TRANSACTION_ID = XS.MTRAN_MATERIAL_TRANSACTION_ID)
      */
      --   AND XS.MTRAN_MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
      --   AND XS.MSER_SERIAL_NUMBER_ID IN (&SERIAL_NUMBER_ID)
   AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE XS.MTRAN_MATERIAL_TRANSACTION_ID =
               RX.MTRAN_MATERIAL_TRANSACTION_ID
           AND RX.NUM_RECEIPT_AP_MRCV IN (&NUM_RECEIPT_AP_MRCV))
   FOR UPDATE
