SELECT II.SUPPLIER_ITEM_ID
      ,II.ITEM_ITEM_ID
      ,APPS.MAM_ITEMS_CTRL_PKG.GET_DESCRIPTION(II.ITEM_ITEM_ID) AS ITEM
      ,(SELECT A2.COD_BRAND_BRND || ': ' || A2.DES_BRAND_BRND
          FROM MAM.MAM_BRANDS A2
         WHERE II.BRND_COD_BRAND_BRND = A2.COD_BRAND_BRND) AS BRAND
      ,II.FLG_ORG_MSUPI
      ,II.FLG_SUPPLIER_MSUPI
      ,II.FLG_MANUFACTURE_MSUPI
       
      ,II.NAM_DRG_MSUPI
      ,II.COD_CUSTOMER_ITEM_NUMBER_MSUPI
      ,II.DES_CUSTOMER_ITEM_MSUPI
      ,II.CCNTR_COD_CC_CCNTR
      ,II.DES_US_CUSTOMER_ITEM_MSUPI
      ,II.FLG_ENABLED_MSUPI
      ,II.NAM_POS_MSUPI
      ,II.NAM_MNF_MSUPI
      ,II.NUM_QCTM_MSUPI
      ,II.TYP_SUGG_ITEM_MSUPI
      ,II.DAT_DISABLE_MSUPI
      ,TO_CHAR(II.DAT_DISABLE_MSUPI
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_DISABLE_MSUPI_H
      ,II.NAM_DRG_SUP_MSUPI
      ,II.BRND_COD_BRAND_BRND
      ,II.COD_REVISION_MSUPI
      ,II.COD_EQU_MSUPI
      ,II.COD_SER_MSUPI
      ,II.ATTACH_ID
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.LAST_CHANGE_TS
      ,II.MODULE_NAME
      ,II.OS_USERNAME
  FROM --
        MAM.MAM_SUPPLIER_ITEMS
       --
         II
 WHERE 1 = 1
       AND EXISTS (SELECT NULL
          FROM MAM.MAM_ITEMS A11
         WHERE II.ITEM_ITEM_ID = A11.ITEM_ID
               AND A11.COD_ITEM IN (&COD_ITEM))
-- for update
