SELECT H.REQUEST_HEADER_ID
      ,H.NUM_REQUEST_MREQH
      ,H.LKP_STA_HEADER_MREQH
      ,H.*
  FROM MAM.MAM_REQUEST_HEADERS H
 WHERE 1 = 1
      --       AND H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_LIKE')
   AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_IN)
/*
       AND EXISTS
 (SELECT NULL
          FROM --
                MAM.MAM_REQUEST_LINES
               --
                 L
         WHERE L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
               AND ( --
                &COD_ITEM IS NULL OR EXISTS
                ( --
                     SELECT NULL
                       FROM MAM.MAM_ITEMS I
                      WHERE L.ITEM_ITEM_ID = I.ITEM_ID
                           --       AND I.COD_ITEM = TRIM(&COD_ITEM)
                            AND I.COD_ITEM LIKE TRIM(&COD_ITEM) || '%'
                     --
                     )
               --
               )
--
 )
*/
   FOR UPDATE
--
;
SELECT L.REQUEST_LINE_ID
      ,( --
        SELECT I.COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE L.ITEM_ITEM_ID = I.ITEM_ID
        --
        ) AS COD_ITEM
      ,( --
        SELECT H.NUM_REQUEST_MREQH
          FROM MAM.MAM_REQUEST_HEADERS H
         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
        --
        ) AS NUM_REQUEST_MREQH
      ,(SELECT SUM(X.QTY_PRIMARY_MTRAN)
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
         WHERE X.MREQL_REQUEST_LINE_ID = L.REQUEST_LINE_ID) AS QTY_DELIVERED
      ,L.QTY_MREQL
      ,L.MREQH_REQUEST_HEADER_ID
      ,L.DAT_END_REQUIREMENT_MREQL
      ,TO_CHAR(L.DAT_END_REQUIREMENT_MREQL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_END_REQUIREMENT_MREQL_H
      ,L.ITEM_ITEM_ID
      ,L.NUM_LINE_MREQL
      ,L.LKP_STA_LINE_MREQL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REQUEST_LINES')
                                                    ,UPPER('LKP_STA_LINE_MREQL')
                                                    ,L.LKP_STA_LINE_MREQL) AS LKP_STA_LINE_MREQL_DES
      ,L.DAT_STATUS_MREQL
      ,TO_CHAR(L.DAT_STATUS_MREQL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_STATUS_MREQL_H
      ,L.QTY_PRIMARY_MREQL
      ,L.CCNTR_COD_CC_CCNTR
      ,L.MSINV_NAM_SUB_INVENTORY_MSIFOR
      ,L.QTY_DELIVERED_MREQL
      ,L.DAT_START_REQUIREMENT_MREQL
      ,TO_CHAR(L.DAT_START_REQUIREMENT_MREQL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_START_REQUIREMENT_MREQL_H
      ,L.NAM_UNIT_OF_MEASURE_MREQL
      ,L.NAM_UNIT_OF_MEASURE_PRIMARY_MR
      ,L.TXT_COMMENT_MREQL
      ,L.THPRT_COD_THPRT
      ,L.DES_ITEM_MREQL
--,L.TXT_RETURN_REQEUST_MREQL
  FROM --
        MAM.MAM_REQUEST_LINES
       -- JRN.MAM_REQUEST_LINES_JRN
       --
         L
 WHERE 1 = 1 --
      --
      --AND (&LKP_STA_LINE_MREQL IS NULL OR L.LKP_STA_LINE_MREQL != &LKP_STA_LINE_MREQL)
      --       AND       (&REQUEST_LINE_ID IS NULL OR L.REQUEST_LINE_ID = &REQUEST_LINE_ID)
      /*
            
             AND ( --
              &COD_ITEM IS NULL OR EXISTS
              ( --
                   SELECT NULL
                     FROM MAM.MAM_ITEMS I
                    WHERE L.ITEM_ITEM_ID = I.ITEM_ID
                         --       AND I.COD_ITEM = TRIM(&COD_ITEM)
                          AND I.COD_ITEM LIKE TRIM(&COD_ITEM) || '%'
                   --
                   )
             --
             )
      */
      
   AND ( --
        EXISTS ( --
                SELECT NULL
                  FROM MAM.MAM_REQUEST_HEADERS H
                 WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
                      --AND H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_LIKE')
                   AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_IN)
                --
                )
       --
       )
   FOR UPDATE
--
;
SELECT (SELECT APPS.MAM_ITEMS_CTRL_PKG.GET_DESCRIPTION(P_ITEM_ID => S.ITEM_ITEM_ID)
          FROM MAM.MAM_SERIAL_NUMBERS S
         WHERE S.SERIAL_NUMBER_ID = RS.MSER_SERIAL_NUMBER_ID) AS ITEM
      ,RS.*
  FROM MAM.MAM_REQUEST_SERIAL_NUMBERS RS
 WHERE 1 = 1
   AND EXISTS ( --
        SELECT NULL
          FROM MAM.MAM_REQUEST_HEADERS H
         INNER JOIN MAM.MAM_REQUEST_LINES L
            ON H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
         WHERE L.REQUEST_LINE_ID = RS.MREQL_REQUEST_LINE_ID
           AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_IN)
        --
        )
--   FOR UPDATE
--
;

SELECT --
 X.MATERIAL_TRANSACTION_ID
,X.ID_TRANSFER_MTRAN AS LINKED_XID
,X.MTYP_TRANSACTION_TYPE_ID AS TT
,APPS.MAM_ITEMS_FLD_PKG.GET_COD_ITEM(P_ITEM_ID => X.ITEM_ITEM_ID_FOR) AS I
,X.MSINV_NAM_SUB_INVENTORY_MSIFOR || ': ' ||
 (SELECT N.DES_MSINV
    FROM MAM.MAM_SUB_INVENTORIES N
   WHERE N.NAM_SUB_INVENTORY_MSINV = X.MSINV_NAM_SUB_INVENTORY_MSIFOR) AS SUB_INVENTORY
,(SELECT L.COD_LOCATOR_MSLOC
    FROM MAM.MAM_SUB_INVENTORY_LOCATORS L
   WHERE L.SUB_INVENTORY_LOCATOR_ID = X.MSLOC_SUB_INVENTORY_LOCATORFOR) AS COD_LOCATOR_MSLOC
,X.SPINV_NUM_SRL_SPINV AS SPINV
,X.ORPYD_ORPYM_NUM_ORD_PYM_ORPYM AS ORPYD
,TO_CHAR(X.DAT_TRANSACTION_MTRAN
        ,'YYYY/MM/DD HH24:MI:SS'
        ,'NLS_CALENDAR=PERSIAN') AS D
,(SELECT RX.NUM_RECEIPT_AP_MRCV || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
,(SELECT RX.RCV_TRANSACTION_ID || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS RCV_TRANSACTION_ID
,X.QTY_PRIMARY_MTRAN AS QTY
,APPS.MAM_EXTERNAL_SYSTEMS_DESC_PKG.GET_BFS_THIRD_PARTIES(P_COD_THPRT => X.THPRT_COD_THPRT) AS THIRD_PARTY
,X.*
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 WHERE 1 = 1
      
   AND X.MREQL_REQUEST_LINE_ID IN
       ( --
        SELECT L.REQUEST_LINE_ID
          FROM MAM.MAM_REQUEST_LINES L
         WHERE 1 = 1 --
           AND ( --
                EXISTS ( --
                        SELECT NULL
                          FROM MAM.MAM_REQUEST_HEADERS H
                         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
                              --AND H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_LIKE')
                           AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_IN)
                        --
                        )
               --
               ) --
        )
 ORDER BY X.DAT_TRANSACTION_MTRAN, X.ITEM_ITEM_ID_FOR, X.QTY_PRIMARY_MTRAN
--   FOR UPDATE
--
;
SELECT RLD.REPLENISH_LINES_DETAIL_ID
      ,RLD.MREQL_REQUEST_LINE_ID
      ,APPS.MAM_REQUEST_HEADERS_FLD_PKG.GET_NUM_REQUEST_MREQH(P_REQUEST_HEADER_ID => APPS.MAM_REQUEST_LINES_FLD_PKG.GET_MREQH_REQUEST_HEADER_ID(P_REQUEST_LINE_ID => RLD.MREQL_REQUEST_LINE_ID)) AS NUM_REQUEST_MREQH
      ,APPS.MAM_REPLENISH_HEADERS_FLD_PKG.GET_NUM_REPLENISHMENT_MREPH(P_REPLENISH_HEADER_ID => APPS.MAM_REPLENISH_LINES_FLD_PKG.GET_MREPH_REPLENISH_HEADER_ID(P_REPLENISH_LINE_ID => RLD.MREPL_REPLENISH_LINE_ID)) AS NUM_REPLENISHMENT_MREPH
      ,RLD.MREPL_REPLENISH_LINE_ID
      ,RLD.QTY_REPLENISH_MREPD
      ,RLD.ATTACH_ID
      ,RLD.LAST_UPDATE_BY_APP_USER
      ,RLD.LAST_UPDATE_BY_DB_USER
      ,RLD.LAST_UPDATE_DATE
      ,RLD.CREATE_BY_APP_USER
      ,RLD.CREATE_BY_DB_USER
      ,RLD.CREATE_DATE
  FROM MAM.MAM_REPLENISH_LINES_DETAILS RLD
 WHERE 1 = 1
   AND RLD.MREQL_REQUEST_LINE_ID IN
       ( --
        SELECT L.REQUEST_LINE_ID
          FROM MAM.MAM_REQUEST_LINES L
         WHERE 1 = 1 --
           AND ( --
                EXISTS ( --
                        SELECT NULL
                          FROM MAM.MAM_REQUEST_HEADERS H
                         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
                              --AND H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_LIKE')
                           AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_IN)
                        --
                        )
               --
               ) --
        )
--
   FOR UPDATE;
