SELECT II.ITEM_PRQSAFETY_FACTOR_ID
      ,II.ITEM_ITEM_ID
       /*
       ,II.FLG_REPAIRABLE_MIPSF
       ,II.FLG_MAKEABLE_MIPSF
       ,II.FLG_LOW_CONSUMPTION_MIPSF
       ,II.FLG_DECOMPOSABLE_MIPSF
       ,II.FLG_SINGLE_MOUNT_MIPSF
       ,II.NUM_SAFETY_FACTOR_MIPSF
       ,II.CREATE_DATE
       ,II.CREATE_BY_DB_USER
       ,II.CREATE_BY_APP_USER
       ,II.LAST_UPDATE_DATE
       ,II.LAST_UPDATE_BY_DB_USER
       ,II.LAST_UPDATE_BY_APP_USER
       ,II.ATTACH_ID
       */
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_FLG_REPAIRABLE(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_FLG_REPAIRABLE
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_FLG_MAKEABLE(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_FLG_MAKEABLE
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_FLG_LOW_CONSUMPTION(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_FLG_LOW_CONSUMPTION
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_FLG_DECOMPOSABLE(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_FLG_DECOMPOSABLE
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_FLG_SINGLE_MOUNT(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_FLG_SINGLE_MOUNT
      ,MAM_ITEM_PRQSAFETY_FACTORS_PKG.GET_NUM_SAFETY_FACTOR(P_ITEM_PRQSAFETY_FACTOR_ID => II.ITEM_PRQSAFETY_FACTOR_ID) GET_NUM_SAFETY_FACTOR

  FROM MAM.MAM_ITEM_PRQSAFETY_FACTORS II
 WHERE 1 = 1
   AND II.ITEM_ITEM_ID IN ( --
                           SELECT A1.ITEM_ID
                             FROM MAM.MAM_ITEMS A1
                            WHERE 1 = 1
                                 -- AND A1.COD_ITEM IN (&COD_ITEM)
                              AND A1.ITEM_ID IN (&ITEM_ID)
                           
                           --
                           )
--   FOR UPDATE
