SELECT II.ITEM_SUB_INVENTORY_ID
      ,II.ITEM_ITEM_ID
      ,(SELECT A1.COD_ITEM || ': ' || A1.DES_ITEM
          FROM MAM.MAM_ITEMS A1
         WHERE II.ITEM_ITEM_ID = A1.ITEM_ID) AS ITEM
      ,II.MSINV_NAM_SUB_INVENTORY_MSINV
      ,(SELECT A2.DES_MSINV
          FROM MAM.MAM_SUB_INVENTORIES A2
         WHERE II.MSINV_NAM_SUB_INVENTORY_MSINV =
               A2.NAM_SUB_INVENTORY_MSINV) AS INV
      ,II.MSLOC_SUB_INVENTORY_LOCATOR_ID
      ,(SELECT A3.COD_LOCATOR_MSLOC
          FROM MAM.MAM_SUB_INVENTORY_LOCATORS A3
         WHERE II.MSLOC_SUB_INVENTORY_LOCATOR_ID =
               A3.SUB_INVENTORY_LOCATOR_ID) AS COD_LOCATOR_MSLOC
      ,II.FLG_PRIMARY_SUBINVENTORY_MIINV
      ,II.COD_REVISION_MIINV
      ,II.COD_INVENTORY_PLANNING_MIINV
      ,II.COD_LOT_MIINV
      ,II.COD_SERIAL_NUMBER_MIINV
      ,II.QTY_MIN_MINMAX_MIINV
      ,II.QTY_MAX_MINMAX_MIINV
      ,II.QTY_MINIMUM_ORDER_MIINV
      ,II.QTY_MAXIMUM_ORDER_MIINV
      ,II.TYP_SOURCE_MIINV
  FROM MAM.MAM_ITEM_SUB_INVENTORIES II
 WHERE 1 = 1
  
             AND EXISTS (SELECT NULL
                FROM MAM.MAM_ITEMS A11
               WHERE II.ITEM_ITEM_ID = A11.ITEM_ID
                     AND A11.COD_ITEM IN (&COD_ITEM))
  
--AND II.MSINV_NAM_SUB_INVENTORY_MSINV IN (&NAM_SUB_INVENTORY)
      --   AND II.MSLOC_SUB_INVENTORY_LOCATOR_ID IS NOT NULL
--   AND II.ITEM_SUB_INVENTORY_ID IN (&ITEM_SUB_INVENTORY_ID)
--   FOR UPDATE
