SELECT II.MEASUREMENT_UNIT_ID
      ,II.NAM_UNIT_OF_MEASURE_MUOM
      ,II.COD_UNIT_OF_MEASURE_MUOM
      ,II.DES_MUOM
      ,II.FLG_BASE_UOM_MUOM
      ,II.DAT_DISABLE_MUOM
      ,TO_CHAR(II.DAT_DISABLE_MUOM
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_DISABLE_MUOM_H
      ,II.LKP_CLASS_MUOM
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_MEASUREMENT_UNITS')
                                                    ,UPPER('LKP_CLASS_MUOM')
                                                    ,II.LKP_CLASS_MUOM) AS LKP_CLASS_MUOM_DES
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.LKP_TYPE_ENERGY_MUOM
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_MEASUREMENT_UNITS')
                                                    ,UPPER('LKP_TYPE_ENERGY_MUOM')
                                                    ,II.LKP_TYPE_ENERGY_MUOM) AS LKP_TYPE_ENERGY_MUOM_DES
      ,II.ATTACH_ID
      ,II.MUOM_MEASUREMENT_UNIT_ID
  FROM MAM.MAM_MEASUREMENT_UNITS II
 WHERE 1 = 1
      --       AND MEASUREMENT_UNIT_ID = &MEASUREMENT_UNIT_ID
   AND FND.FND_REPLACE_STRING(TRIM(II.NAM_UNIT_OF_MEASURE_MUOM)) LIKE '%' || FND.FND_REPLACE_STRING(TRIM('&nam_unit_of_measure_muom')) || '%'
--   AND FND.FND_REPLACE_STRING(II.COD_UNIT_OF_MEASURE_MUOM) LIKE  '%' || UPPER(FND.FND_REPLACE_STRING('&COD_UNIT_OF_MEASURE_MUOM')) || '%'
   FOR UPDATE
