SELECT II.TRANSACTION_SNAPSHOT_ID AS ID_
      ,II.ITEM_ITEM_ID
      ,A1.COD_ITEM
      ,II.MSINV_NAM_SUB_INVENTORY_MSINV AS INV
      ,II.MSLOC_SUB_INVENTORY_LOCATOR_ID AS LID
      ,A3.COD_LOCATOR_MSLOC
      ,II.DAT_SNAPSHOT_MXSNP
      ,TO_CHAR(II.DAT_SNAPSHOT_MXSNP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_SNAPSHOT_MXSNP_H
      ,II.NUM_QTY_MXSNP
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.ATTACH_ID
  FROM MAM.MAM_TRANSACTION_SNAPSHOTS II
  LEFT OUTER JOIN MAM.MAM_ITEMS A1
    ON II.ITEM_ITEM_ID = A1.ITEM_ID
  LEFT OUTER JOIN MAM.MAM_SUB_INVENTORIES A2
    ON II.MSINV_NAM_SUB_INVENTORY_MSINV = A2.NAM_SUB_INVENTORY_MSINV
  LEFT OUTER JOIN MAM.MAM_SUB_INVENTORY_LOCATORS A3
    ON II.MSLOC_SUB_INVENTORY_LOCATOR_ID = A3.SUB_INVENTORY_LOCATOR_ID
 WHERE 1 = 1
   AND II.ITEM_ITEM_ID IN (&ITEM_ID)
