SELECT H.REPLENISH_HEADER_ID
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REPLENISH_HEADERS')
                                                    ,UPPER('LKP_STA_REPLENISHMENT_MREPH')
                                                    ,H.LKP_STA_REPLENISHMENT_MREPH) AS LKP_STA_REPLENISHMENT_MREPHDES
       
      ,H.NUM_REPLENISHMENT_MREPH
      ,H.DAT_REPLENISHMENT_MREPH
      ,H.*
  FROM MAM.MAM_REPLENISH_HEADERS
       --
        H
 WHERE 1 = 1
       AND H.NUM_REPLENISHMENT_MREPH LIKE '&NUM_REPLENISHMENT_MREPH'
       /*
       AND ( --
            SELECT NULL MAM.MAM_REPLENISH_LINES L WHERE L.MREPH_REPLENISH_HEADER_ID = H.REPLENISH_HEADER_ID AND L.REPLENISH_LINE_ID = &REPLENISH_LINE_ID
            --
            )
       */     
--   FOR UPDATE
--
;
