SELECT S.NUM_MITST
      ,S.COD_MITST
      ,S.DES_MITST
      ,S.MITST_NUM_MITST
      ,S.DES_US_MITST
      ,S.CREATE_DATE
      ,S.CREATE_BY_DB_USER
      ,S.CREATE_BY_APP_USER
      ,S.LAST_UPDATE_DATE
      ,S.LAST_UPDATE_BY_DB_USER
      ,S.LAST_UPDATE_BY_APP_USER
      ,S.ATTACH_ID
  FROM MAM.MAM_ITEM_STRUCTURES S
 WHERE 1 = 1
       AND S.NUM_MITST LIKE '&NUM_MITST'
 ORDER BY TO_NUMBER(S.NUM_MITST)
