SELECT AR.LOG_AFFECTED_RECORD_ID
      ,AR.MLAFR_LOG_ID
      ,AR.NAM_TABLE_MLAFR
      ,AR.NAM_KEY_FIELD_MLAFR
      ,AR.NAM_VAL_MLAFR
      ,APPS.MAM_LOGS_FLD_PKG.GET_NAM_CALLER_ROUTINE_MLOGS(P_LOG_ID => AR.MLAFR_LOG_ID) AS NAM_CALLER_ROUTINE_MLOGS
      ,APPS.MAM_LOGS_FLD_PKG.GET_TXT_PARAMETERS_MLOGS(P_LOG_ID => AR.MLAFR_LOG_ID) AS TXT_PARAMETERS_MLOGS
  FROM MAM.MAM_LOG_AFFECTED_RECORDS AR
 WHERE 1 = 1
      --   AND ar.mlafr_log_id IN (&LOG_ID)
   AND AR.CREATE_DATE > TRUNC(SYSDATE)
 ORDER BY AR.MLAFR_LOG_ID DESC
--
;
