/*
SELECT *
  FROM MAM.MAM_PHYSICAL_SUBINVENTORIES PS
 WHERE PS.MPINV_PHYSICAL_INVENTORY_ID IN (&PHYSICAL_INVENTORY_ID);
*/
SELECT II.PHYSICAL_ADJUSTMENT_ID
      ,APPS.MAM_ITEMS_CTRL_PKG.GET_DESCRIPTION(II.ITEM_ITEM_ID) AS ITEM
      ,II.ITEM_ITEM_ID
      ,II.COD_LOT_MPADJ
      ,II.COD_SERIAL_NUMBER_MPADJ
      ,II.LKP_COD_AUTO_APPROVE_MPADJ
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_PHYSICAL_ADJUSTMENTS')
                                                    ,UPPER('LKP_COD_AUTO_APPROVE_MPADJ')
                                                    ,II.LKP_COD_AUTO_APPROVE_MPADJ) AS LKP_COD_AUTO_APPROVE_MPADJ_DES
      ,II.NUM_COUNT_MPADJ
      ,II.MPSUB_PHYSICAL_SUBINVENTORY_ID
      ,II.COD_REVISION_MPADJ
      ,II.LKP_STA_APPROVAL_MPADJ
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_PHYSICAL_ADJUSTMENTS')
                                                    ,UPPER('LKP_STA_APPROVAL_MPADJ')
                                                    ,II.LKP_STA_APPROVAL_MPADJ) AS LKP_STA_APPROVAL_MPADJ_DES
      ,II.QTY_ADJUSTMENT_MPADJ
      ,II.QTY_COUNT_MPADJ
      ,II.QTY_SYSTEM_MPADJ
      ,II.EMPLY_NUM_PRSN_EMPLY
      ,II.QTY_ONHAND_MPADJ
      ,II.COD_PASSPORT_MPADJ
      ,II.DATE_PRODUCT_MPADJ
      ,II.QTY_TKS_MPADJ
      ,II.QTY_WID_MPADJ
      ,II.QTY_SIZE1_MPADJ
      ,II.QTY_SIZE2_MPADJ
      ,II.QTY_LTH_MPADJ
      ,II.QTY_QLY_MPADJ
      ,II.QTY_BAR_NO_MPADJ
      ,II.NUM_PACK_MPADJ
      ,II.CODE_PASSPORT_MPADJ
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.MSINV_NAM_SUB_INVENTORY_MSINV
      ,II.MSLOC_SUB_INVENTORY_LOCATOR_ID
      ,II.ATTACH_ID
  FROM MAM.MAM_PHYSICAL_ADJUSTMENTS II

 WHERE 1 = 1
   AND II.MPSUB_PHYSICAL_SUBINVENTORY_ID IN (&PHYSICAL_SUBINVENTORY_ID)
   AND II.ITEM_ITEM_ID IN (&ITEM_ID)
 ORDER BY II.MPSUB_PHYSICAL_SUBINVENTORY_ID
         ,II.ITEM_ITEM_ID
         ,II.MSINV_NAM_SUB_INVENTORY_MSINV
         ,II.MSLOC_SUB_INVENTORY_LOCATOR_ID
         ,II.NUM_COUNT_MPADJ
--
for update
;
