SELECT IDPV.ITEM_DYN_PRPRTY_VAL_ID
      ,IDPV.ITEM_ITEM_ID
      ,APPS.MAM_ITEMS_FLD_PKG.GET_COD_ITEM(P_ITEM_ID => IDPV.ITEM_ITEM_ID) AS COD_ITEM
      ,IDPV.MTDPN_TBL_DYN_PRPRTY_NAME_ID
      ,APPS.MAM_DYN_PROPERTY_NAMES_FLD_PKG.GET_NAM_PROPERTY_MDPRN(P_DYN_PROPERTY_NAME_ID => APPS.MAM_TBL_DYN_PRPRTY_NMS_FLD_PKG.GET_MTDPN_PROPERTY_NAME_ID(P_TBL_DYN_PRPRTY_NAME_ID => IDPV.MTDPN_TBL_DYN_PRPRTY_NAME_ID)) AS PROPERTY_NAME
      ,IDPV.TXT_VALUE_MIDPV
      ,APPS.MAM_ITEMS_FLD_PKG.GET_DESCRIPTION(P_ITEM_ID => IDPV.ITEM_ITEM_ID) AS ITEM
      ,IDPV.CREATE_DATE
      ,IDPV.CREATE_BY_DB_USER
      ,IDPV.CREATE_BY_APP_USER
      ,IDPV.LAST_UPDATE_DATE
      ,IDPV.LAST_UPDATE_BY_DB_USER
      ,IDPV.LAST_UPDATE_BY_APP_USER
      ,IDPV.ATTACH_ID
  FROM MAM.MAM_ITEM_DYN_PRPRTY_VALS IDPV
 WHERE 1 = 1
   AND IDPV.ITEM_ITEM_ID IN
       (SELECT ITEM_ID FROM MAM.MAM_ITEMS I WHERE I.COD_ITEM IN (&COD_ITEM))
