SELECT II.ONHAND_QUANTITY_ID
      ,II.ITEM_ITEM_ID
      ,(SELECT I.COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = II.ITEM_ITEM_ID) I
      ,II.MSINV_NAM_SUB_INVENTORY_MSINV
      ,II.NUM_PIE_MONH
      ,II.QTY_MONH
      ,II.MLOT_LOT_NUMBER_ID
      ,II.MSER_SERIAL_NUMBER_ID
      ,II.MSLOC_SUB_INVENTORY_LOCATOR_ID
      ,II.LKP_COD_LOST_MONH
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_ONHAND_QUANTITIES')
                                                    ,UPPER('LKP_COD_LOST_MONH')
                                                    ,II.LKP_COD_LOST_MONH) AS LKP_COD_LOST_MONH_DES
      ,II.COD_REVISION_MONH
      ,II.LKP_STA_PENDING_MONH
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_ONHAND_QUANTITIES')
                                                    ,UPPER('LKP_STA_PENDING_MONH')
                                                    ,II.LKP_STA_PENDING_MONH) AS LKP_STA_PENDING_MONH_DES
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.ATTACH_ID
  FROM MAM.MAM_ONHAND_QUANTITIES II
 WHERE 1 = 1
       AND II.ITEM_ITEM_ID =
       (SELECT ITEM_ID
              FROM MAM.MAM_ITEMS I
             WHERE I.COD_ITEM = TRIM('&COD_ITEM'))
--   FOR UPDATE
