SELECT 
II.COD_BRAND_BRND
,II.DES_BRAND_BRND
,II.LKP_COD_COUNT_BRND
,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_BRANDS'),UPPER('LKP_COD_COUNT_BRND'),II.LKP_COD_COUNT_BRND) AS LKP_COD_COUNT_BRND_DES
,II.FLG_FOREIGN_BRND
,II.LKP_TYP_BRND
,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_BRANDS'),UPPER('LKP_TYP_BRND'),II.LKP_TYP_BRND) AS LKP_TYP_BRND_DES
,II.CREATE_DATE
,II.CREATE_BY_DB_USER
,II.CREATE_BY_APP_USER
,II.LAST_UPDATE_DATE
,II.LAST_UPDATE_BY_DB_USER
,II.LAST_UPDATE_BY_APP_USER
,II.ATTACH_ID
 FROM MAM.MAM_BRANDS II 
--WHERE
