SELECT RLD.REPLENISH_LINES_DETAIL_ID
      ,RLD.MREQL_REQUEST_LINE_ID
      ,RLD.MREPL_REPLENISH_LINE_ID
      ,RLD.QTY_REPLENISH_MREPD
      ,RLD.ATTACH_ID
      ,RLD.LAST_UPDATE_BY_APP_USER
      ,RLD.LAST_UPDATE_BY_DB_USER
      ,RLD.LAST_UPDATE_DATE
      ,RLD.CREATE_BY_APP_USER
      ,RLD.CREATE_BY_DB_USER
      ,RLD.CREATE_DATE
  FROM MAM.MAM_REPLENISH_LINES_DETAILS RLD
 WHERE 1 = 1
AND RLD.MREQL_REQUEST_LINE_ID IN(&REQUEST_LINE_ID)
--
;
