SELECT (SELECT 1
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
                 INNER JOIN MAM.MAM_SERIAL_NUMBERS S
                    ON RXS.NUM_SERIAL_MRCVS = S.COD_SERIAL_NUMBER_MSER
                   AND RXS.ITEM_ITEM_ID = S.ITEM_ITEM_ID
                 WHERE S.SERIAL_NUMBER_ID = FA.MSER_SERIAL_NUMBER_ID)) AS MAM_RCV_SERIAL_TRANSACTIONS
      ,(SELECT 1
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                 WHERE XS.MSER_SERIAL_NUMBER_ID = FA.MSER_SERIAL_NUMBER_ID)) AS MAM_TRANSACTION_SERIAL_NUMBERS
      ,(SELECT SUM(SIGN(X.QTY_PRIMARY_MTRAN))
          FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
         INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
            ON XS.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID
         WHERE XS.MSER_SERIAL_NUMBER_ID = FA.MSER_SERIAL_NUMBER_ID) AS SUM_QTY
      ,FA.*
  FROM FIA.FIA_FIXED_ASSETS FA
 WHERE 1 = 1
   AND (EXISTS
        (SELECT NULL
           FROM MAM.MAM_ITEMS I
          INNER JOIN MAM.MAM_SERIAL_NUMBERS S
             ON S.ITEM_ITEM_ID = I.ITEM_ID
          WHERE S.SERIAL_NUMBER_ID = FA.MSER_SERIAL_NUMBER_ID
            AND I.COD_ITEM IN (&COD_ITEM)) OR &COD_ITEM IS NULL) --
--                    
--       AND (FA.MSER_SERIAL_NUMBER_ID IN (&SERIAL_NUMBER_ID) OR  &SERIAL_NUMBER_ID IS NULL) --
 ORDER BY FA.NUM_ASSET_FIXAS
--
;
SELECT (SELECT I.COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = S.ITEM_ITEM_ID) AS ITEM
      ,(SELECT FA.NUM_ASSET_FIXAS
          FROM FIA.FIA_FIXED_ASSETS FA
         WHERE FA.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID) AS NUM_ASSET_FIXAS
      ,S.SERIAL_NUMBER_ID
      ,S.ITEM_ITEM_ID
      ,S.COD_SERIAL_NUMBER_MSER
      ,(SELECT SUM(SIGN(X.QTY_PRIMARY_MTRAN))
          FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
         INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
            ON XS.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID
         WHERE XS.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID) AS SUM_QTY
       
      ,S.LKP_STA_CURRENT_MSER
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SERIAL_NUMBERS')
                                                    ,UPPER('LKP_STA_CURRENT_MSER')
                                                    ,S.LKP_STA_CURRENT_MSER) AS LKP_STA_CURRENT_MSER_DES
      ,(SELECT 'USED'
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
                 WHERE XS.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID)) AS XS
      ,(SELECT 'USED'
          FROM DUAL
         WHERE EXISTS
         (SELECT NULL
                  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
                 WHERE RXS.ITEM_ITEM_ID = S.ITEM_ITEM_ID
                   AND RXS.NUM_SERIAL_MRCVS = S.COD_SERIAL_NUMBER_MSER)) AS RXS
      ,S.DAT_DISABLE_MSER
      ,TO_CHAR(S.DAT_DISABLE_MSER
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_DISABLE_MSER_H
      ,S.NAM_SUB_INVENTORY_MSER
      ,S.STA_OLD_MSER
      ,S.COD_REVISION_MSER
  FROM MAM.MAM_SERIAL_NUMBERS S
 WHERE 1 = 1
   AND (EXISTS
        (SELECT NULL
           FROM MAM.MAM_ITEMS I
          WHERE I.ITEM_ID = S.ITEM_ITEM_ID
            AND I.COD_ITEM IN (&COD_ITEM)) OR &COD_ITEM IS NULL) --
--                    
--       AND (S.SERIAL_NUMBER_ID IN (&SERIAL_NUMBER_ID) OR       &SERIAL_NUMBER_ID IS NULL) --
 ORDER BY S.SERIAL_NUMBER_ID
--   FOR UPDATE

--
;
