SELECT *
  FROM ( --
        SELECT FT.WORK_FLOW_FROM_TO_ID
               ,MAM_WORK_FLOW_FROM_TS_CTRL_PKG.GET_PACKAGE_NAME(P_WORK_FLOW_FROM_TO_ID => WORK_FLOW_FROM_TO_ID) AS PKG
               ,RPAD(FT.MWKSP_WORK_FLOW_STEPS_ID_FROM, 6, ' ') || '==' ||
                FT.TXT_CAPTION_MWFFT || '=>' ||
                LPAD(FT.MWKSP_WORK_FLOW_STEPS_ID_TO, 6, ' ') AS FROM_ID_BY_CAPTION_TO_ID
               ,RPAD(APPS.MAM_WORK_FLOW_STEPS_CTRL_PKG.GET_COD_STEP_MWKSP(P_WORK_FLOW_STEP_ID => FT.MWKSP_WORK_FLOW_STEPS_ID_FROM)
                    ,6
                    ,' ') || '==' || FT.TXT_CAPTION_MWFFT || '=>' ||
                RPAD(APPS.MAM_WORK_FLOW_STEPS_CTRL_PKG.GET_COD_STEP_MWKSP(P_WORK_FLOW_STEP_ID => FT.MWKSP_WORK_FLOW_STEPS_ID_TO)
                    ,6
                    ,' ') AS FROM_COD_BY_CAPTION_TO_COD
               ,APPS.MAM_WORK_FLOW_STEPS_CTRL_PKG.GET_DESCRIPTION(P_WORK_FLOW_STEP_ID => FT.MWKSP_WORK_FLOW_STEPS_ID_FROM) AS FROM_
               ,FT.TXT_CAPTION_MWFFT AS BY_
               ,APPS.MAM_WORK_FLOW_STEPS_CTRL_PKG.GET_DESCRIPTION(P_WORK_FLOW_STEP_ID => FT.MWKSP_WORK_FLOW_STEPS_ID_TO) AS TO_
          FROM MAM.MAM_WORK_FLOW_FROM_TOS FT
        --
        )
 ORDER BY FROM_COD_BY_CAPTION_TO_COD
