SELECT CASE
         WHEN EXISTS
          (SELECT NULL
                 FROM APPS.MAM_FMAM4400_NAM_P_I_VIW V
                WHERE V.PHYSICAL_INVENTORY_ID = PI.PHYSICAL_INVENTORY_ID) THEN
          NULL
         ELSE
          'DONE'
       END AS DONE
      ,(SELECT DISTINCT I.NAM_SUB_INVENTORY_MSINV || ': ' || I.DES_MSINV
          FROM MAM.MAM_PHYSICAL_INVENTORY_TAGS T
         INNER JOIN MAM.MAM_SUB_INVENTORIES I
            ON T.MSINV_NAM_SUB_INVENTORY_MSINV = I.NAM_SUB_INVENTORY_MSINV
         WHERE T.MPINV_PHYSICAL_INVENTORY_ID = PI.PHYSICAL_INVENTORY_ID) AS SUB_INVENTORY
      ,PI.PHYSICAL_INVENTORY_ID
      ,(SELECT COUNT(1)
          FROM MAM.MAM_PHYSICAL_INVENTORY_TAGS T63
         WHERE T63.MPINV_PHYSICAL_INVENTORY_ID = PI.PHYSICAL_INVENTORY_ID) AS TAG_COUNT
      ,PI.DAT_PHYSICAL_INVENTORY_MPINV
      ,TO_CHAR(PI.DAT_PHYSICAL_INVENTORY_MPINV
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_PHYSICAL_INVENTORY_MPINV_H
      ,PI.NAM_PHYSICAL_INVENTORY_MPINV
      ,PI.DES_MPINV
      ,PI.FLG_ALL_SUBINVENTORIES_MPINV
      ,PI.FLG_DYNAMIC_TAG_ENTRY_MPINV
      ,PI.FLG_TAG_BASE_MPINV
      ,PI.LKP_FLG_APPROVAL_REQUIRED_MPIN
      ,PI.LKP_FLG_APPROVAL_REQUIRED_MPIN || CASE
         WHEN PI.LKP_FLG_APPROVAL_REQUIRED_MPIN IS NOT NULL THEN
          ': '
       END ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_PHYSICAL_INVENTORIES')
                                                    ,UPPER('LKP_FLG_APPROVAL_REQUIRED_MPIN')
                                                    ,PI.LKP_FLG_APPROVAL_REQUIRED_MPIN) AS LKP_FLG_APPROVAL_REQUIRED__DES
      ,PI.NUM_TAG_INCREMENT_MPINV
      ,PI.NUM_NEXT_TAG_MPINV
  FROM MAM.MAM_PHYSICAL_INVENTORIES PI
 WHERE 1 = 1
--   AND PI.DES_MPINV LIKE '%&des_mpinv%'
--   AND PI.CREATE_DATE > TRUNC(SYSDATE)
 ORDER BY PI.DAT_PHYSICAL_INVENTORY_MPINV DESC
         ,PI.PHYSICAL_INVENTORY_ID        DESC
--   FOR UPDATE
