SELECT *
  FROM MAM.MAM_REQUEST_LOT_NUMBERS RL
 WHERE 1 = 1
   AND EXISTS (SELECT NULL
          FROM MAM.MAM_LOT_NUMBERS L
         INNER JOIN MAM.MAM_ITEMS I
            ON L.ITEM_ITEM_ID = I.ITEM_ID
         WHERE L.LOT_NUMBER_ID = RL.MLOT_LOT_NUMBER_ID
           AND I.COD_ITEM IN (&COD_ITEM))
