SELECT RT.REQUEST_TRANSACTION_ID
      ,RT.MREQL_REQUEST_LINE_ID
      ,(SELECT H.NUM_REQUEST_MREQH
          FROM MAM.MAM_REQUEST_HEADERS H
         INNER JOIN MAM.MAM_REQUEST_LINES L
            ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
         WHERE L.REQUEST_LINE_ID = RT.MREQL_REQUEST_LINE_ID) AS NUM_REQUEST_MREQH
      ,RT.QTY_TRANSACTION_MRTRA
      ,RT.DAT_TRANSACTION_MRTRA
      ,TO_CHAR(RT.DAT_TRANSACTION_MRTRA
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_TRANSACTION_MRTRA_H
      ,RT.TXT_COMMENT_MRTRA
      ,RT.LKP_STATUES_MRTRA
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REQUEST_TRANSACTIONS')
                                                    ,UPPER('LKP_STATUES_MRTRA')
                                                    ,RT.LKP_STATUES_MRTRA) AS LKP_STATUES_MRTRA_DES
      ,RT.LKP_COD_SYSTEM_MRTRA
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_REQUEST_TRANSACTIONS')
                                                    ,UPPER('LKP_COD_SYSTEM_MRTRA')
                                                    ,RT.LKP_COD_SYSTEM_MRTRA) AS LKP_COD_SYSTEM_MRTRA_DES
      ,RT.CREATE_DATE
      ,RT.CREATE_BY_DB_USER
      ,RT.CREATE_BY_APP_USER
      ,RT.LAST_UPDATE_DATE
      ,RT.LAST_UPDATE_BY_DB_USER
      ,RT.LAST_UPDATE_BY_APP_USER
      ,RT.ATTACH_ID
  FROM MAM.MAM_REQUEST_TRANSACTIONS RT
 WHERE 1 = 1
      --       AND RT.MREQL_REQUEST_LINE_ID = &MREQL_REQUEST_LINE_ID
       AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_REQUEST_HEADERS H
         INNER JOIN MAM.MAM_REQUEST_LINES L
            ON L.MREQH_REQUEST_HEADER_ID = H.REQUEST_HEADER_ID
         WHERE L.REQUEST_LINE_ID = RT.MREQL_REQUEST_LINE_ID
               AND H.NUM_REQUEST_MREQH IN (&NUM_REQUEST_MREQH))
for update
