SELECT II.PHYSICAL_SUBINVENTORY_ID
      ,II.MPINV_PHYSICAL_INVENTORY_ID
      ,II.MSINV_NAM_SUB_INVENTORY_MSINV
      ,II.COD_FROM_LOCATOR_MPSUB
      ,II.COD_TO_LOCATOR_MPSUB
      ,II.FLG_AVAILABILITY_PUSH_MPSUB
      ,II.FLG_AVAILABILITY_PUT_MPSUB
      ,II.CREATE_DATE
      ,II.CREATE_BY_DB_USER
      ,II.CREATE_BY_APP_USER
      ,II.LAST_UPDATE_DATE
      ,II.LAST_UPDATE_BY_DB_USER
      ,II.LAST_UPDATE_BY_APP_USER
      ,II.NUM_COUNT_ITEM_MPSUB
      ,II.NUM_COUNT_END_PHYSICAL_MPSUB
      ,II.ATTACH_ID
  FROM MAM.MAM_PHYSICAL_SUBINVENTORIES II
 WHERE 1 = 1
   AND II.MPINV_PHYSICAL_INVENTORY_ID IN (&PHYSICAL_INVENTORY_ID)
--    AND II.CREATE_DATE > TRUNC(SYSDATE)
   FOR UPDATE
