SELECT (SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE RXS.ITEM_ITEM_ID = I.ITEM_ID) AS ITEMS
      ,RXS.*
  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
 WHERE 1 = 1
      /*
         AND EXISTS (SELECT NULL
                FROM MAM.MAM_ITEMS I
               WHERE I.COD_ITEM IN (&COD_ITEM)
                 AND RXS.ITEM_ITEM_ID = I.ITEM_ID)
      */
      --AND RXS.MRCV_RCV_TRANSACTION_ID IN (&RCV_TRANSACTION_ID)
   AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.RCV_TRANSACTION_ID = RXS.MRCV_RCV_TRANSACTION_ID
           AND RX.NUM_RECEIPT_AP_MRCV IN (&NUM_RECEIPT_AP_MRCV))
   FOR UPDATE
