SELECT (SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE RXS.ITEM_ITEM_ID = I.ITEM_ID) AS ITEMS
      ,(SELECT F.NUM_ASSET_FIXAS
          FROM FIA.FIA_FIXED_ASSETS F
         INNER JOIN MAM.MAM_SERIAL_NUMBERS S
            ON F.MSER_SERIAL_NUMBER_ID = S.SERIAL_NUMBER_ID
         WHERE S.ITEM_ITEM_ID = RXS.ITEM_ITEM_ID
           AND S.COD_SERIAL_NUMBER_MSER = RXS.NUM_SERIAL_MRCVS) AS NUM_ASSET_FIXAS
      ,(SELECT RX0.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_TRANSACTIONS RX0
         WHERE RX0.RCV_TRANSACTION_ID = RXS.MRCV_RCV_TRANSACTION_ID
           AND ROWNUM = 1) AS NUM_RECEIPT_AP_MRCV
      ,(SELECT SIGN(RX1.QTY_PRIMARY_MRCV)
          FROM MAM.MAM_RCV_TRANSACTIONS RX1
         WHERE RX1.RCV_TRANSACTION_ID = RXS.MRCV_RCV_TRANSACTION_ID
           AND ROWNUM = 1) AS SIGN_
      ,RXS.*
  FROM MAM.MAM_RCV_SERIAL_TRANSACTIONS RXS
 WHERE 1 = 1
      --AND RXS.MRCV_RCV_TRANSACTION_ID IN (&RCV_TRANSACTION_ID)
      
   AND EXISTS
 ( --
        SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.RCV_TRANSACTION_ID = RXS.MRCV_RCV_TRANSACTION_ID
              --                         AND RX.NUM_RECEIPT_AP_MRCV IN (&NUM_RECEIPT_AP_MRCV)
              
           AND EXISTS (SELECT NULL
                  FROM MAM.MAM_ITEMS I
                 WHERE I.COD_ITEM IN (&COD_ITEM)
                   AND RX.ITEM_ITEM_ID = I.ITEM_ID)
        
        --
        )
 ORDER BY 3, RXS.MRCV_RCV_TRANSACTION_ID
   FOR UPDATE
