SELECT I.NAM_SUB_INVENTORY_MSINV
      ,I.DES_MSINV
      ,I.FLG_AVAILABILITY_PUT_MSINV
      ,I.COD_RESERVABLE_MSINV
      ,I.COD_LOCATOR_MSINV
      ,I.COD_PICKING_ORDER_MSINV
      ,I.COD_ASSET_INVENTORY_MSINV
      ,I.FLG_DEPRECIABLE_MSINV
      ,I.FLG_AVAILABILITY_PUSH_MSINV
      ,I.LKP_RESPONSIBILITY_RESTRICTED_
/*      
      ,I.LKP_RESPONSIBILITY_RESTRICTED_ || CASE
         WHEN I.LKP_RESPONSIBILITY_RESTRICTED_ IS NOT NULL THEN
          ': '
       END ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SUB_INVENTORIES')
                                                    ,UPPER('LKP_RESPONSIBILITY_RESTRICTED_')
                                                    ,I.LKP_RESPONSIBILITY_RESTRICTED_) AS LKP_RESPONSIBILITY_RESTRIC_DES
*/
      ,I.LKP_TYP_SUB_INVENTORY_MSINV
/*
      ,I.LKP_TYP_SUB_INVENTORY_MSINV || CASE
         WHEN I.LKP_TYP_SUB_INVENTORY_MSINV IS NOT NULL THEN
          ': '
       END ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SUB_INVENTORIES')
                                                    ,UPPER('LKP_TYP_SUB_INVENTORY_MSINV')
                                                    ,I.LKP_TYP_SUB_INVENTORY_MSINV) AS LKP_TYP_SUB_INVENTORY_MSIN_DES
*/
      ,I.LKP_TYPE_ITEM_MSINV
/*
      ,I.LKP_TYPE_ITEM_MSINV || CASE
         WHEN I.LKP_TYPE_ITEM_MSINV IS NOT NULL THEN
          ': '
       END ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_SUB_INVENTORIES')
                                                    ,UPPER('LKP_TYPE_ITEM_MSINV')
                                                    ,I.LKP_TYPE_ITEM_MSINV) AS LKP_TYPE_ITEM_MSINV_DES
*/
      ,I.LOCAT_LOCATION_ID
  FROM MAM.MAM_SUB_INVENTORIES I
 ORDER BY I.NAM_SUB_INVENTORY_MSINV
--   FOR UPDATE
