SELECT O.ORDER_ID
      ,O.NUM_PGV_PUROR AS NUM_PGV
      ,O.LKP_TYP_ORD_PUROR AS TYP_ORD
      ,O.LKP_COD_STEP_PUROR AS COD_STEP
      ,O.SUPCO_THPRT_COD_THPRT
      ,OP.PUROP_ID
      ,OP.NUM_POS_PUROP AS NUM_POS
      ,OP.QTY_CMM_ORD_PUROP AS QTY_CMM
      ,OP.QTY_DLV_PUROP AS QTY_DLV
      ,OP.QTY_CMM_ORD_PUROP - OP.QTY_DLV_PUROP AS DIFF
       
      ,RP.PURRP_ID
      ,R.MDELP_DELIVERY_POINTS_ID || ': ' ||
       (SELECT '˜Ï ' || DP.COD_DELIVEY_POINT_MDELP || ' ãÑ˜Ò åÒíäå ' ||
               DP.CCNTR_COD_CC_CCNTR
          FROM MAM.MAM_DELIVERY_POINTS DP
         WHERE DP.DELIVERY_POINTS_ID = R.MDELP_DELIVERY_POINTS_ID) AS DP
      ,R.LKP_TYP_DEBT_PURRQ
      ,(SELECT DP.CCNTR_COD_CC_CCNTR || ': ' || U.NAM_USER_USRS || '->' ||
               M.NAM_USER_USRS
          FROM MAM.MAM_DELIVERY_POINTS DP
          LEFT OUTER JOIN FND.FND_USERS U
            ON DP.USER_NAME_MDELP = U.IDE_USER_USRS
          LEFT OUTER JOIN FND.FND_USERS M
            ON DP.USER_MANAGER_ID_MDELP = M.IDE_USER_USRS
        
         WHERE DP.DELIVERY_POINTS_ID = R.MDELP_DELIVERY_POINTS_ID) AS DP
      ,I.ITEM_ID
      ,I.COD_ITEM
      ,I.DES_ITEM
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_ITEMS')
                                                    ,UPPER('LKP_STA_INVENTORY_ITEM')
                                                    ,I.LKP_STA_INVENTORY_ITEM) AS LKP_STA_INVENTORY_ITEM_DES
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_ITEMS')
                                                    ,UPPER('LKP_ROUTING_RECEIPT_ITEM')
                                                    ,I.LKP_ROUTING_RECEIPT_ITEM) AS LKP_ROUTING_RECEIPT_ITEM_DES
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('MAM_ITEMS')
                                                    ,UPPER('LKP_TYPE_WAY_RCV_ITEM')
                                                    ,I.LKP_TYPE_WAY_RCV_ITEM) AS LKP_TYPE_WAY_RCV_ITEM_DES
      ,R.LKP_TYP_REQ_PURRQ || ':' ||
       APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUR_REQUESTS')
                                                    ,UPPER('LKP_TYP_REQ_PURRQ')
                                                    ,R.LKP_TYP_REQ_PURRQ) AS LKP_TYP_REQ_PURRQ_DES
  FROM PUR.PUR_ORDERS O
 INNER JOIN PUR.PUR_ORDER_POSITIONS OP
    ON O.ORDER_ID = OP.PUROR_ORDER_ID
 INNER JOIN PUR.PUR_REQUEST_POSITIONS RP
    ON OP.PURRP_PURRP_ID = RP.PURRP_ID
 INNER JOIN MAM.MAM_ITEMS I
    ON RP.ITEM_ITEM_ID = I.ITEM_ID
 INNER JOIN PUR.PUR_REQUESTS R
    ON R.NUM_PGV_PURRQ = RP.PURRQ_NUM_PGV_PURRQ

 WHERE 1 = 1
       AND O.NUM_MDF_PUROR = 0
       AND O.NUM_PGV_PUROR IN (&NUM_PGV_PUROR)
--       AND OP.PUROP_ID = &PUROP_ID
--       AND I.COD_ITEM = &COD_ITEM
-- AND OP.QTY_CMM_ORD_PUROP > NVL(OP.QTY_CMM_DLV_PUROP, 0)
--       AND I.COD_ITEM LIKE '6%'
