SELECT WI.WYBIL_WAYBILL_ID
      ,WI.NUM_SEQ_WYBIT
      ,WI.ITEM_ITEM_ID
      ,WI.NUM_RECEIPT_INV_WYBIT
      ,APPS.PUA_WAYBILLS_FLD_PKG.GET_NUM_WYB_GOV_WYBIL(P_WAYBILL_ID => WI.WYBIL_WAYBILL_ID) AS NUM_WYB_GOV_WYBIL
      ,APPS.PUA_WAYBILLS_FLD_PKG.GET_QTY_REL_ITEM_WYBIL(P_WAYBILL_ID => WI.WYBIL_WAYBILL_ID) AS QTY_REL_ITEM_WYBIL
      ,APPS.PUA_WAYBILLS_FLD_PKG.GET_QTY_ITEM_WYBIL(P_WAYBILL_ID => WI.WYBIL_WAYBILL_ID) AS QTY_REL_ITEM_WYBIL
      ,WI.QTY_ITEM_WYBIT
      ,WI.QTY_MODIFY_WYBIT
      ,WI.QTY_NET_ITEM_WYBIT
      ,WI.QTY_REL_ITEM_WYBIT
      ,WI.NUM_ITEM_WYBIT
      ,APPS.MAM_ITEMS_CTRL_PKG.GET_DESCRIPTION(P_ITEM_ID => WI.ITEM_ITEM_ID) AS ITEM
       /*
       ,WI.CREATE_DATE
       ,WI.CREATE_BY_DB_USER
       ,WI.CREATE_BY_APP_USER
       ,WI.LAST_UPDATE_DATE
       ,WI.LAST_UPDATE_BY_DB_USER
       ,WI.LAST_UPDATE_BY_APP_USER
       ,WI.ATTACH_ID
       */
      ,WI.COD_EXT_COIL_WYBIT
      ,WI.PUROP_PUROP_ID
      ,WI.MTBIT_WAYBILL_ITEM_ID
  FROM PUA.PUA_WAYBILL_ITEMS WI
 WHERE 1 = 1
      --   AND WI.NUM_RECEIPT_INV_WYBIT IN (&NUM_RECEIPT_INV_WYBIT)
      --    AND WI.NUM_RECEIPT_INV_WYBIT LIKE '%&NUM_RECEIPT_INV_WYBIT%'
      --   AND WI.WYBIL_WAYBILL_ID IN (&WAYBILL_ID)
      --   AND WI.WYBIL_WAYBILL_ID = PUA_WAYBILLS_FLD_PKG.GET_PK_BY_NUM_WYB_GOV_WYBIL(P_NUM_WYB_GOV_WYBIL => &NUM_WYB_GOV_WYBIL)
      --    AND WI.CREATE_DATE > TRUNC(SYSDATE)
   AND EXISTS
 (SELECT NULL
          FROM PUA.PUA_WAYBILLS W
         WHERE W.WAYBILL_ID = WI.WYBIL_WAYBILL_ID
           AND W.NUM_WYB_GOV_WYBIL LIKE '&num_wyb_gov_wybil%')
   FOR UPDATE
 ORDER BY WI.WYBIL_WAYBILL_ID DESC
