SELECT W.WAYBILL_ID
      ,W.LKP_FLG_WYB_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_FLG_WYB_WYBIL')
                                                    ,W.LKP_FLG_WYB_WYBIL) AS LKP_FLG_WYB_WYBIL_DES
      ,W.NUM_WYB_GOV_WYBIL
       --       ,W.PUROR_ORDER_ID
      ,APPS.PUR_ORDERS_CTRL_PKG.GET_DESCRIPTION(P_ORDER_ID => W.PUROR_ORDER_ID) AS ORDER_
      ,W.ORDHE_COD_ORD_ORDHE
      ,W.DAT_ENTR_WYBIL
      ,TO_CHAR(W.DAT_ENTR_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_ENTR_WYBIL_H
       --        ,W.THPRT_COD_THPRT
      ,APPS.MAM_EXTERNAL_SYSTEMS_DESC_PKG.GET_BFS_THIRD_PARTIES(P_COD_THPRT => W.THPRT_COD_THPRT) AS THIRD_PARTY
      ,W.THPRT_COD_THPRT_CARRIER_BY
      ,W.GEPOS_GEOGRAPHIC_POSITION_ID
      ,APPS.MAM_EXTERNAL_SYSTEMS_DESC_PKG.GET_PDS_GEOGRAPHIC_POSITIONS(P_GEOGRAPHIC_POSITION_ID => W.GEPOS_GEOGRAPHIC_POSITION_ID) AS GEOGRAPHIC_POSITION
      ,W.TYP_WYB_WYBIL
      ,W.ORDHE_FLG_DB_ORDHE
      ,W.PURLC_NUM_LC_PURLC
      ,W.AMN_WEI_WYBIL
      ,W.AMN_WYB_WYBIL
      ,W.COD_CLR_WYBIL
      ,W.COD_CNTR_WYBIL
      ,W.DAT_CLR_WYBIL
      ,TO_CHAR(W.DAT_CLR_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_CLR_WYBIL_H
      ,W.DAT_EXIT_WYBIL
      ,TO_CHAR(W.DAT_EXIT_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_EXIT_WYBIL_H
      ,W.DAT_WYB_WYBIL
      ,TO_CHAR(W.DAT_WYB_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_WYB_WYBIL_H
      ,W.DES_WYB_WYBIL
      ,W.LKP_COD_PEN_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_COD_PEN_WYBIL')
                                                    ,W.LKP_COD_PEN_WYBIL) AS LKP_COD_PEN_WYBIL_DES
      ,W.LKP_LINE_POOL_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_LINE_POOL_WYBIL')
                                                    ,W.LKP_LINE_POOL_WYBIL) AS LKP_LINE_POOL_WYBIL_DES
      ,W.LKP_POOL_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_POOL_WYBIL')
                                                    ,W.LKP_POOL_WYBIL) AS LKP_POOL_WYBIL_DES
      ,W.LKP_STA_MAM_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_STA_MAM_WYBIL')
                                                    ,W.LKP_STA_MAM_WYBIL) AS LKP_STA_MAM_WYBIL_DES
      ,W.LKP_TYP_CAR_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_TYP_CAR_WYBIL')
                                                    ,W.LKP_TYP_CAR_WYBIL) AS LKP_TYP_CAR_WYBIL_DES
      ,W.LKP_TYP_EMPTY_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_TYP_EMPTY_WYBIL')
                                                    ,W.LKP_TYP_EMPTY_WYBIL) AS LKP_TYP_EMPTY_WYBIL_DES
      ,W.LKP_TYP_MAT_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_TYP_MAT_WYBIL')
                                                    ,W.LKP_TYP_MAT_WYBIL) AS LKP_TYP_MAT_WYBIL_DES
      ,W.NAM_CARRIER_WYBIL
      ,W.NAM_DRV_WYBIL
      ,W.NUM_CAR_WYBIL
      ,W.QTY_CAL_WYBIL
      ,W.QTY_CAR_ITEM_WYBIL
      ,W.QTY_CAR_WYBIL
      ,W.QTY_ITEM_WYBIL
      ,W.QTY_KIL_WYBIL
      ,W.QTY_REL_ITEM_WYBIL
       /*
       ,w.CREATE_DATE
       ,w.CREATE_BY_DB_USER
       ,w.CREATE_BY_APP_USER
       ,w.LAST_UPDATE_DATE
       ,w.LAST_UPDATE_BY_DB_USER
       ,w.LAST_UPDATE_BY_APP_USER
       */
      ,W.NUM_WYB_SUPP_WYBIL
      ,W.NUM_BASCULE_IN_WYBIL
      ,W.NUM_BASCULE_OUT_WYBIL
       --,w.ATTACH_ID
      ,W.CCNTR_COD_CC_CCNTR
      ,W.TEL_DRV_WYBIL
      ,W.DAT_EMTY_WYBIL
      ,TO_CHAR(W.DAT_EMTY_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_EMTY_WYBIL_H
      ,W.DAT_QTY_CAR_ITEM_WYBIL
      ,TO_CHAR(W.DAT_QTY_CAR_ITEM_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_QTY_CAR_ITEM_WYBIL_H
      ,W.DAT_QTY_CAR_WYBIL
      ,TO_CHAR(W.DAT_QTY_CAR_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_QTY_CAR_WYBIL_H
      ,W.DAT_EXIT_CAR_WYBIL
      ,TO_CHAR(W.DAT_EXIT_CAR_WYBIL
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_EXIT_CAR_WYBIL_H
      ,W.NAM_SRC_SHIPMENT_WYBIL
      ,W.NAM_DEST_SHIPMENT_WYBIL
      ,W.COD_USER_BASCL_IN_WYBIL
      ,W.COD_USER_BASCL_OUT_WYBIL
      ,W.NUM_TOZIN_WYBIL
      ,W.TXT_DRIVER_BANK_CARD_WYBIL
      ,W.TXT_DRIVER_BANK_ACCOUNT_WYBIL
      ,W.NAM_DRIVER_BANK_OWNER_WYBIL
      ,W.MTBIL_WAYBILL_ID
      ,W.LKP_COD_SYS_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_COD_SYS_WYBIL')
                                                    ,W.LKP_COD_SYS_WYBIL) AS LKP_COD_SYS_WYBIL_DES
      ,W.LKP_TYP_WYB_IN_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_TYP_WYB_IN_WYBIL')
                                                    ,W.LKP_TYP_WYB_IN_WYBIL) AS LKP_TYP_WYB_IN_WYBIL_DES
      ,W.LKP_TYP_WYB_OUT_WYBIL
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUA_WAYBILLS')
                                                    ,UPPER('LKP_TYP_WYB_OUT_WYBIL')
                                                    ,W.LKP_TYP_WYB_OUT_WYBIL) AS LKP_TYP_WYB_OUT_WYBIL_DES
      ,W.COD_STA_WYBIL
      ,W.NUM_SRL_WYB_WYBIL
      ,W.TXT_COMMENT_WYBIL
      ,W.COD_ACN_WYBIL
      ,W.COD_NATIONAL_DRV_WYBIL
      ,W.COD_LIST_WYBIL
      ,W.NAM_USER_CONFIRM_DSCHRGE_WYBIL
      ,W.COD_UUID_BANK_WYBIL
  FROM PUA.PUA_WAYBILLS W
 WHERE 1 = 1
AND W.NUM_WYB_GOV_WYBIL LIKE '&num_wyb_gov_wybil%'
      --   AND W.WAYBILL_ID IN (&WAYBILL_ID)
      --   AND W.CREATE_DATE > TRUNC(SYSDATE)
/*      
   AND EXISTS (SELECT NULL
          FROM PUA.PUA_WAYBILL_ITEMS WI
         WHERE WI.WYBIL_WAYBILL_ID = W.WAYBILL_ID
           AND WI.NUM_RECEIPT_INV_WYBIT IS NULL)
*/           
 ORDER BY W.WAYBILL_ID DESC
--   FOR UPDATE
