SELECT OP.PUROP_ID
      ,OP.MUOM_MEASUREMENT_UNIT_ID
      ,(SELECT U.NAM_UNIT_OF_MEASURE_MUOM
          FROM MAM.MAM_MEASUREMENT_UNITS U
         WHERE U.MEASUREMENT_UNIT_ID = OP.MUOM_MEASUREMENT_UNIT_ID) AS NAM_UNIT_OF_MEASURE_MUOM
      ,OP.PUROR_ORDER_ID
      ,(SELECT O.NUM_PGV_PUROR
          FROM PUR.PUR_ORDERS O
         WHERE O.ORDER_ID = OP.PUROR_ORDER_ID) AS NUM_PGV_PUROR
      ,OP.PURRP_PURRP_ID
      ,(SELECT I.ITEM_ID || ' ' || '{' || U.NAM_UNIT_OF_MEASURE_MUOM || '}' ||
              I.COD_ITEM || ': ' || I.DES_ITEM
       
         FROM PUR.PUR_REQUEST_POSITIONS RP
        INNER JOIN MAM.MAM_ITEMS I
           ON RP.ITEM_ITEM_ID = I.ITEM_ID
        INNER JOIN MAM.MAM_MEASUREMENT_UNITS U
           ON I.MUOM_MEASUREMENT_UNIT_ID = U.MEASUREMENT_UNIT_ID
        WHERE RP.PURRP_ID = OP.PURRP_PURRP_ID)
      ,OP.NUM_POS_PUROP
      ,OP.NUM_MDF_PUROP
      ,OP.DIFTY_COD_DIF_DIFTY
      ,OP.TARIF_NUM_PGV_TARIF
      ,OP.DAT_STR_VALD_PUROP
      ,TO_CHAR(OP.DAT_STR_VALD_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_STR_VALD_PUROP_H
      ,OP.DAT_END_VALD_PUROP
      ,TO_CHAR(OP.DAT_END_VALD_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_END_VALD_PUROP_H
      ,OP.QTY_WNTD_ORD_PUROP
      ,OP.QTY_CMM_ORD_PUROP
      ,OP.QTY_CMM_DLV_PUROP
      ,OP.AMN_UNI_PRC_PUROP
      ,OP.DAT_MDF_PUROP
      ,TO_CHAR(OP.DAT_MDF_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_MDF_PUROP_H
      ,OP.AMN_MDF_PUROP
      ,OP.QTY_MDF_PUROP
      ,OP.DAT_INS_POS_PUROP
      ,TO_CHAR(OP.DAT_INS_POS_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_INS_POS_PUROP_H
      ,OP.QTY_MDF_PRC_PUROP
      ,OP.DAT_EXPD_PUROP
      ,TO_CHAR(OP.DAT_EXPD_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_EXPD_PUROP_H
      ,OP.QTY_DLV_PUROP
      ,OP.QTY_DIF_PUROP
      ,OP.NUM_DAYS_DLV_PUROP
      ,OP.QTY_PER_DLV_PUROP
      ,OP.COD_MAT_REPL_PUROP
      ,OP.COD_MAT_SUP_PUROP
      ,OP.AMN_DISC_PUROP
      ,OP.LKP_TYP_PKG_PUROP
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUR_ORDER_POSITIONS')
                                                    ,UPPER('LKP_TYP_PKG_PUROP')
                                                    ,OP.LKP_TYP_PKG_PUROP) AS LKP_TYP_PKG_PUROP_DES
      ,OP.QTY_RATE_UOM_PUROP
      ,OP.CREATE_DATE
      ,OP.CREATE_BY_DB_USER
      ,OP.CREATE_BY_APP_USER
      ,OP.LAST_UPDATE_DATE
      ,OP.LAST_UPDATE_BY_DB_USER
      ,OP.LAST_UPDATE_BY_APP_USER
       --      ,OP.FLG_ENCUMBERD_PUROP
      ,OP.ATTACH_ID
       --      ,OP.COD_REVISION_PUROP
      ,OP.LKP_UNIT_TEST_ITEM_PUROP
      ,APPS.APP_FND_LOOKUP_PKG.GET_FARSI_MEANING_FUN(UPPER('PUR_ORDER_POSITIONS')
                                                    ,UPPER('LKP_UNIT_TEST_ITEM_PUROP')
                                                    ,OP.LKP_UNIT_TEST_ITEM_PUROP) AS LKP_UNIT_TEST_ITEM_PUROP_DES
/*
      ,OP.QTY_TEL_PUROP
      ,OP.AMN_TOT_MDF4_PUROP
      ,OP.DAT_STR_BUDGET_PUROP
      ,TO_CHAR(OP.DAT_STR_BUDGET_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_STR_BUDGET_PUROP_H
      ,OP.DAT_END_BUDGET_PUROP
      ,TO_CHAR(OP.DAT_END_BUDGET_PUROP
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DAT_END_BUDGET_PUROP_H
      ,OP.AMN_ACTUAL_SELECTED_RCV_PUROP
*/
  FROM PUR.PUR_ORDER_POSITIONS OP
 WHERE 1 = 1
   AND OP.NUM_MDF_PUROP = 0
   AND OP.PUROR_ORDER_ID =
       (SELECT O.ORDER_ID
          FROM PUR.PUR_ORDERS O
         WHERE O.NUM_MDF_PUROR = 0
           AND O.NUM_PGV_PUROR IN (&NUM_PGV_PUROR))

/*
   AND EXISTS (SELECT NULL
          FROM PUR.PUR_REQUEST_POSITIONS RP
         INNER JOIN MAM.MAM_ITEMS I
            ON RP.ITEM_ITEM_ID = I.ITEM_ID
         WHERE OP.PURRP_PURRP_ID = RP.PURRP_ID
           AND I.COD_ITEM IN (&COD_ITEM))
*/
