SELECT Q.ONHAND_QUANTITY_ID
      ,Q.ITEM_ITEM_ID
      ,(SELECT I.COD_ITEM || ': ' || I.DES_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = Q.ITEM_ITEM_ID) AS ITEM
      ,Q.MSINV_NAM_SUB_INVENTORY_MSINV
      ,Q.QTY_MONH
      ,Q.MSLOC_SUB_INVENTORY_LOCATOR_ID
  FROM MAM.MAM_ONHAND_QUANTITIES Q
 WHERE --
 1 = 1
-- AND Q.ITEM_ITEM_ID = (SELECT ITEM_ID FROM MAM.MAM_ITEMS I WHERE I.COD_ITEM = '&COD_ITEM')
 AND Q.QTY_MONH > 0
--   FOR UPDATE
