SELECT H.*
  FROM MAM.MAM_REQUEST_HEADERS H
 WHERE H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_MREQH')
   FOR UPDATE
--
; --
SELECT ( --
        SELECT H.NUM_REQUEST_MREQH
          FROM MAM.MAM_REQUEST_HEADERS H
         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
        --
        ) AS NUM_REQUEST_MREQH
      ,( --
        SELECT H.LKP_STA_HEADER_MREQH
          FROM MAM.MAM_REQUEST_HEADERS H
         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
        --
        ) AS LKP_STA_HEADER_MREQH
      ,L.REQUEST_LINE_ID
      ,L.LKP_STA_LINE_MREQL
      ,L.NUM_LINE_MREQL
      ,( --
        SELECT I.COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE L.ITEM_ITEM_ID = I.ITEM_ID) AS ITEM
      ,(SELECT SUM(ABS(X.QTY_PRIMARY_MTRAN))
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
         WHERE X.MREQL_REQUEST_LINE_ID = L.REQUEST_LINE_ID) AS SQ_DELIVERED
      ,L.*
  FROM MAM.MAM_REQUEST_LINES L
 WHERE 1 = 1
       AND EXISTS
 ( --
        SELECT NULL
          FROM MAM.MAM_REQUEST_HEADERS H
         WHERE H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
               AND H.NUM_REQUEST_MREQH LIKE TRIM('&NUM_REQUEST_MREQH')
        --
        )
--       AND L.LKP_STA_LINE_MREQL = 6
   FOR UPDATE
--
;
