SELECT
/*
 (SELECT U.NAM_USER_USRS
    FROM FND.FND_USERS U
   WHERE U.IDE_USER_USRS = RX.CREATE_BY_APP_USER) AS NAM_USER_USRS
,
*/
 (SELECT O.NUM_PGV_PUROR
    FROM PUR.PUR_ORDERS O
   INNER JOIN PUR.PUR_ORDER_POSITIONS OP
      ON O.ORDER_ID = OP.PUROR_ORDER_ID
   WHERE OP.PUROP_ID = RX.PUROP_PUROP_ID) AS NUM_PGV_PUROR
,(SELECT I.COD_ITEM FROM MAM.MAM_ITEMS I WHERE I.ITEM_ID = RX.ITEM_ITEM_ID) I
,(SELECT U.NAM_UNIT_OF_MEASURE_MUOM
    FROM MAM.MAM_ITEMS I
   INNER JOIN MAM.MAM_MEASUREMENT_UNITS U
      ON I.MUOM_MEASUREMENT_UNIT_ID = U.MEASUREMENT_UNIT_ID
   WHERE I.ITEM_ID = RX.ITEM_ITEM_ID) NAM_UNIT_OF_MEASURE_MUOM
,TO_CHAR(RX.DAT_TRANSACTION_MRCV, 'YYYY/MM/DD HH24:MI:SS', 'NLS_CALENDAR=PERSIAN') D
,(CASE
   WHEN 1 = 0
        OR RX.ORPYDORPYM_NUM_ORD_PYM_ORPYM IS NOT NULL
        OR RX.ORPYD_NUM_SEQ_ORPYD IS NOT NULL
        OR RX.DAT_STL_MRCV IS NOT NULL
        OR RX.SPINV_NUM_SRL_SPINV IS NOT NULL THEN
    'Don''t Change!'
 END) AS ERR
,RX.SPINV_NUM_SRL_SPINV AS SPINV
,RX.ORPYD_NUM_SEQ_ORPYD AS SEQ_ORPYD
,RX.ORPYDORPYM_NUM_ORD_PYM_ORPYM AS ORPYM
,RX.DAT_STL_MRCV
,RX.NUM_RECEIPT_AP_MRCV
,RX.LKP_TYP_TRANSACTION_MRCV
,RX.RCV_TRANSACTION_ID
,RX.PARENT_TRANSACTION_ID_MRCV
,RX.QTY_PRIMARY_MRCV
,RX.MTRAN_MATERIAL_TRANSACTION_ID
,RX.PCN_FALL_MRCV
,RX.PCN_FALL_AMOUNT_MRCV
,RX.PUROP_PUROP_ID
,RX.PAKNR_PACKING_NUMBER_ID
,RX.BUSUN_COD_BUSUN
,RX.ORPYD_NUM_SEQ_ORPYD
 --      ,RX.ORPYDORPYM_NUM_ORD_PYM_ORPYM
 --      ,RX.DLVNH_DELIVERY_NOTE_ID
,RX.COD_REVISION_MRCV
,RX.QTY_BILLED_MRCV
,RX.ITEM_ITEM_ID
,RX.LKP_COD_INSPECTION_STATUS_MRCV
,RX.CCNTR_COD_CC_CCNTR
,RX.MSINV_NAM_SUB_INVENTORY_MSINV
,RX.MSLOC_SUB_INVENTORY_LOCATOR_ID
,RX.MTREA_TRANSACTION_REASON_ID
,RX.DAT_TRANSACTION_MRCV
,RX.QTY_MRCV
,RX.AMN_ACTUAL_MRCV
,RX.AMN_STIMATE_MRCV
,RX.DAT_STL_MRCV
,RX.LKP_COD_DESTINATION_TYPE_MRCV
,RX.LKP_COD_FCT_MRCV
,RX.LKP_COD_SOURCE_DOCUMENT_MRCV
,RX.LKP_ROUTING_RECEIPT_MRCV
,RX.NAM_UNIT_OF_MEASURE_MRCV
,RX.NAM_UNIT_OF_MEASURE_PRIMARY_MR
,RX.NUM_RECEIPT_INV_MRCV
,RX.NUM_RMA_REFERENCE_MRCV
,RX.TXT_COMMENT_MRCV
  FROM --
        MAM.MAM_RCV_TRANSACTIONS
       --APPS.MAM_RCV_TRANSACTIONS_JRN 
       --jrn.MAM_RCV_TRANSACTIONS_JRN 
       --
         RX
 WHERE 1 = 1
      --       AND RX.PUROP_PUROP_ID = &PUROP_ID
      
       AND RX.NUM_RECEIPT_AP_MRCV = TRIM(&NUM_RECEIPT_AP_MRCV)
/*
       AND EXISTS (SELECT NULL
          FROM PUR.PUR_ORDER_POSITIONS OP
         INNER JOIN PUR.PUR_ORDERS O
            ON OP.PUROR_ORDER_ID = O.ORDER_ID
         WHERE RX.PUROP_PUROP_ID = OP.PUROP_ID
               AND O.NUM_PGV_PUROR = &NUM_PGV_PUROR)
*/
-- AND RX.MTRAN_MATERIAL_TRANSACTION_ID IN (&MTRAN_MATERIAL_TRANSACTION_ID)
--AND RX.ITEM_ITEM_ID=(SELECT I.ITEM_ID FROM MAM.MAM_ITEMS I WHERE I.COD_ITEM=&COD_ITEM) 
 ORDER BY RX.NUM_RECEIPT_AP_MRCV
         ,RX.DAT_TRANSACTION_MRCV
         ,RX.RCV_TRANSACTION_ID

--   FOR UPDATE
;
SELECT X.MATERIAL_TRANSACTION_ID
      ,X.QTY_PRIMARY_MTRAN
      ,X.NAM_UNIT_OF_MEASURE_PRIMARY_MT
      ,X.QTY_TRANSACTION_MTRAN
      ,X.NAM_UNIT_OF_MEASURE_MTRAN
  FROM --
       MAM.MAM_MATERIAL_TRANSACTIONS X
 WHERE 1 = 1
      --       AND RX.PUROP_PUROP_ID = &PUROP_ID
      
       AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE X.MATERIAL_TRANSACTION_ID = RX.MTRAN_MATERIAL_TRANSACTION_ID
               AND RX.NUM_RECEIPT_AP_MRCV = TRIM(&NUM_RECEIPT_AP_MRCV))
/*
       AND EXISTS (SELECT NULL
          FROM PUR.PUR_ORDER_POSITIONS OP
         INNER JOIN PUR.PUR_ORDERS O
            ON OP.PUROR_ORDER_ID = O.ORDER_ID
            inner join MAM.MAM_RCV_TRANSACTIONS RX
        on  RX.PUROP_PUROP_ID = OP.PUROP_ID
         WHERE      AND O.NUM_PGV_PUROR = &NUM_PGV_PUROR)
*/
 ORDER BY X.MATERIAL_TRANSACTION_ID
--   FOR UPDATE
