SELECT XS.MTRAN_MATERIAL_TRANSACTION_ID
      ,S.*
  FROM MAM.MAM_SERIAL_NUMBERS S
  LEFT OUTER JOIN MAM.MAM_TRANSACTION_SERIAL_NUMBERS XS
    ON S.SERIAL_NUMBER_ID = XS.MSER_SERIAL_NUMBER_ID
 WHERE S.SERIAL_NUMBER_ID = &SERIAL_NUMBER_ID;
SELECT rXS.Rcv_Serial_Transaction_Id
      ,S.*
  FROM MAM.MAM_SERIAL_NUMBERS S
  LEFT OUTER JOIN MAM.Mam_Rcv_Serial_Transactions rXS
    ON S.SERIAL_NUMBER_ID = rXS.MSER_SERIAL_NUMBER_ID
 WHERE S.SERIAL_NUMBER_ID = &SERIAL_NUMBER_ID;
 

