SELECT --
 J.MATERIAL_TRANSACTION_ID AS XID
,J.ID_TRANSFER_MTRAN AS LINKED_XID
,J.MTYP_TRANSACTION_TYPE_ID AS TT
,(SELECT I.COD_ITEM
    FROM MAM.MAM_ITEMS I
   WHERE I.ITEM_ID = J.ITEM_ITEM_ID_FOR) I
,J.MSINV_NAM_SUB_INVENTORY_MSIFOR AS SUB_INVENTORY
,J.JRN_OPERATION
,TO_CHAR(J.JRN_DATETIME, 'YYYY/MM/DD HH24:MI:SS', 'NLS_CALENDAR=PERSIAN') AS JD
 
,J.SPINV_NUM_SRL_SPINV AS SPINV
,J.ORPYD_ORPYM_NUM_ORD_PYM_ORPYM AS ORPYD
,TO_CHAR(J.DAT_TRANSACTION_MTRAN
        ,'YYYY/MM/DD HH24:MI:SS'
        ,'NLS_CALENDAR=PERSIAN') AS D
,(SELECT RX.NUM_RECEIPT_AP_MRCV || ': ' || RX.RCV_TRANSACTION_ID
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = J.MATERIAL_TRANSACTION_ID) AS RX
,(SELECT RX.NUM_RECEIPT_AP_MRCV || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = J.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
,(SELECT RX.RCV_TRANSACTION_ID || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = J.MATERIAL_TRANSACTION_ID) AS RCV_TRANSACTION_ID
,J.QTY_PRIMARY_MTRAN AS QTY
,J.*
  FROM JRN.MAM_MATERIAL_TRANSACTIONS_JRN J
 WHERE 1 = 1
   AND J.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
/*      
       AND (j.MATERIAL_TRANSACTION_ID IN
       (SELECT MATERIAL_TRANSACTION_ID
               FROM MAM.MAM_MATERIAL_TRANSACTIONS X0
              WHERE X0.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
             UNION
             SELECT X2.ID_TRANSFER_MTRAN
               FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
              WHERE X2.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)) OR
       j.ID_TRANSFER_MTRAN IN (&MATERIAL_TRANSACTION_ID))
*/
/*      
       AND EXISTS
 ( --
        SELECT NULL
          FROM MAM.MAM_REQUEST_HEADERS H
         INNER JOIN MAM.MAM_REQUEST_LINES L
            ON H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
         WHERE j.MREQL_REQUEST_LINE_ID = L.REQUEST_LINE_ID
               AND H.NUM_REQUEST_MREQH LIKE '&NUM_REQUEST_MREQH' --
        )
*/
-- AND TRUNC(j.CREATE_DATE) = TRUNC(SYSDATE)
--AND TRUNC(j.CREATE_DATE) =trunc(TO_DATE('&CREATE_DATE', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN'))
/*
       AND TRUNC(j.DAT_TRANSACTION_MTRAN) =
       TRUNC(TO_DATE('&Dat_Transaction_Mtran'
                        ,'YYYY/MM/DD'
                        ,'NLS_CALENDAR=PERSIAN'))
*/
--       AND j.MTYP_TRANSACTION_TYPE_ID = 26
--       AND j.CCNTR_COD_CC_CCNTR = &CCNTR_COD_CC_CCNTR
/*      
       AND J.ITEM_ITEM_ID_FOR =
       (SELECT ITEM_ID
              FROM MAM.MAM_ITEMS I
             WHERE I.COD_ITEM = TRIM('&COD_ITEM'))
       AND j.MSINV_NAM_SUB_INVENTORY_MSIFOR = &NAM_SUB_INVENTORY
       AND j.MSLOC_SUB_INVENTORY_LOCATORFOR = &SUB_INVENTORY_LOCATOR_ID
*/
--       AND j.OS_USERNAME = '&OS_USERNAME'
--       AND j.CREATE_BY_APP_USER = UPPER('&CREATE_BY_APP_USER')
--       AND j.MREQL_REQUEST_LINE_ID IN (&MREQL_REQUEST_LINE_ID)
-- AND j.CREATE_DATE > TRUNC(SYSDATE) AND (j.CREATE_BY_APP_USER = 'IRISA_RABBANI' OR j.OS_USERNAME = 'h.rabbani')
 ORDER BY J.MATERIAL_TRANSACTION_ID DESC, J.JRN_ID
/*
j.DAT_TRANSACTION_MTRAN
        ,j.ITEM_ITEM_ID_FOR
        ,j.QTY_PRIMARY_MTRAN
        */
--   FOR UPDATE
--SELECT TO_DATE('&TO_DATE', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN')  FROM DUAL
--SELECT  TO_CHAR('&TO_CHAR', 'YYYY/MM/DD HH24:MI:SS','NLS_CALENDAR=PERSIAN') FROM DUAL
