SELECT --
 X.MATERIAL_TRANSACTION_ID || ',' AS XID
,X.ID_TRANSFER_MTRAN AS LINKED_XID
,X.MTYP_TRANSACTION_TYPE_ID AS TT
,(SELECT I.COD_ITEM
    FROM MAM.MAM_ITEMS I
   WHERE I.ITEM_ID = X.ITEM_ITEM_ID_FOR) I
,X.MSINV_NAM_SUB_INVENTORY_MSIFOR AS SUB_INVENTORY
,CASE
   WHEN EXISTS
    (SELECT DISTINCT XV.NUM_DCM_TRVAL
           FROM WAC.WAC_TRANSACTION_VALUES XV
          WHERE XV.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) THEN
    'WAC_TRANSACTION_VALUES'
 END AS WAC_TRANSACTION_VALUES
,X.SPINV_NUM_SRL_SPINV AS SPINV
,X.ORPYD_ORPYM_NUM_ORD_PYM_ORPYM AS ORPYD
,TO_CHAR(X.DAT_TRANSACTION_MTRAN
        ,'YYYY/MM/DD HH24:MI:SS'
        ,'NLS_CALENDAR=PERSIAN') AS D
,(SELECT RX.NUM_RECEIPT_AP_MRCV || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT_AP_MRCV
,(SELECT RX.RCV_TRANSACTION_ID || ','
    FROM MAM.MAM_RCV_TRANSACTIONS RX
   WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS RCV_TRANSACTION_ID
,X.QTY_PRIMARY_MTRAN AS QTY
,X.*
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X
 WHERE 1 = 1
      --AND X.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
      
       AND (X.MATERIAL_TRANSACTION_ID IN
       (SELECT MATERIAL_TRANSACTION_ID
               FROM MAM.MAM_MATERIAL_TRANSACTIONS X0
              WHERE X0.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
             UNION
             SELECT X2.ID_TRANSFER_MTRAN
               FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
              WHERE X2.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)) OR
       X.ID_TRANSFER_MTRAN IN (&MATERIAL_TRANSACTION_ID))

/*      
       AND EXISTS
 ( --
        SELECT NULL
          FROM MAM.MAM_REQUEST_HEADERS H
         INNER JOIN MAM.MAM_REQUEST_LINES L
            ON H.REQUEST_HEADER_ID = L.MREQH_REQUEST_HEADER_ID
         WHERE X.MREQL_REQUEST_LINE_ID = L.REQUEST_LINE_ID
               AND H.NUM_REQUEST_MREQH LIKE '&NUM_REQUEST_MREQH' --
        )
*/
-- AND TRUNC(X.CREATE_DATE) = TRUNC(SYSDATE)
--AND TRUNC(X.CREATE_DATE) =trunc(TO_DATE('&CREATE_DATE', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN'))
/*
       AND TRUNC(X.DAT_TRANSACTION_MTRAN) =
       TRUNC(TO_DATE('&Dat_Transaction_Mtran'
                        ,'YYYY/MM/DD'
                        ,'NLS_CALENDAR=PERSIAN'))
*/
--       AND X.MTYP_TRANSACTION_TYPE_ID = 26
--       AND X.CCNTR_COD_CC_CCNTR = &CCNTR_COD_CC_CCNTR
/*
       AND X.ITEM_ITEM_ID_FOR =
       (SELECT ITEM_ID
              FROM MAM.MAM_ITEMS I
             WHERE I.COD_ITEM = TRIM('&COD_ITEM'))
*/
--       AND X.OS_USERNAME = '&OS_USERNAME'
--       AND X.CREATE_BY_APP_USER = UPPER('&CREATE_BY_APP_USER')
--       AND X.MREQL_REQUEST_LINE_ID IN (&MREQL_REQUEST_LINE_ID)
-- AND X.CREATE_DATE > TRUNC(SYSDATE) AND (X.CREATE_BY_APP_USER = 'IRISA_RABBANI' OR X.OS_USERNAME = 'h.rabbani')
 ORDER BY X.DAT_TRANSACTION_MTRAN
         ,X.ITEM_ITEM_ID_FOR
         ,X.QTY_PRIMARY_MTRAN
--   FOR UPDATE
--SELECT TO_DATE('&TO_DATE', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN')  FROM DUAL
--SELECT  TO_CHAR('&TO_CHAR', 'YYYY/MM/DD HH24:MI:SS','NLS_CALENDAR=PERSIAN') FROM DUAL
--TO_DATE('&TO_DATE', 'YYYY/MM/DD', 'NLS_CALENDAR=PERSIAN')
--TO_DATE('&TO_CHAR', 'YYYY/MM/DD HH24:MI:SS','NLS_CALENDAR=PERSIAN')
