SELECT W.*, ROWID
  FROM PUA.PUA_WAYBILLS W
 WHERE EXISTS (SELECT WI.*, ROWID
          FROM PUA.PUA_WAYBILL_ITEMS WI
         WHERE WI.NUM_RECEIPT_INV_WYBIT = &NUM_RECEIPT_INV_WYBIT
               AND W.WAYBILL_ID = WI.WYBIL_WAYBILL_ID);
SELECT WI.*, ROWID
  FROM PUA.PUA_WAYBILL_ITEMS WI
 WHERE WI.NUM_RECEIPT_INV_WYBIT = &NUM_RECEIPT_INV_WYBIT;
SELECT R.*, ROWID
  FROM MAM.MAM_RCV_TRANSACTIONS R
 WHERE R.NUM_RECEIPT_INV_MRCV = &NUM_RECEIPT_INV_WYBIT;
