SELECT O.NUM_PGV_PUROR AS "ORDER"
       ,OP1.QTY_CMM_ORD_PUROP - OP1.QTY_CMM_DLV_PUROP AS DIFFERENCE
       ,I.COD_ITEM
       ,I.DES_ITEM

  FROM PUR.PUR_ORDERS O
 INNER JOIN PUR.PUR_ORDER_POSITIONS OP1
    ON O.ORDER_ID = OP1.PUROR_ORDER_ID
 INNER JOIN PUR.PUR_REQUEST_POSITIONS RP1
    ON OP1.PURRP_PURRP_ID = RP1.PURRP_ID
 INNER JOIN MAM.MAM_ITEMS I
    ON RP1.ITEM_ITEM_ID = I.ITEM_ID
 WHERE O.LKP_COD_STEP_PUROR = 75
       AND O.NUM_MDF_PUROR = 0
       and i.cod_item=&cod_item
       AND EXISTS
 (SELECT NULL
          FROM PUR.PUR_ORDER_POSITIONS OP
         INNER JOIN PUR.PUR_REQUEST_POSITIONS RP
            ON OP.PURRP_PURRP_ID = RP.PURRP_ID
         INNER JOIN MAM.MAM_ITEMS I1
            ON RP.ITEM_ITEM_ID = I1.ITEM_ID
         WHERE O.ORDER_ID = OP.PUROR_ORDER_ID
               AND ((OP.QTY_CMM_ORD_PUROP != OP.QTY_CMM_DLV_PUROP
               AND I1.MUOM_MEASUREMENT_UNIT_ID != 760))
               
               
       AND (OP1.QTY_CMM_ORD_PUROP - OP1.QTY_CMM_DLV_PUROP) != 0
)
