SELECT ( --
        SELECT COD_ITEM
          FROM MAM.MAM_ITEMS I
         WHERE I.ITEM_ID = X2.ITEM_ITEM_ID_FOR
        --
        ) AS ITEM
      ,X2.MATERIAL_TRANSACTION_ID
      ,X2.ID_TRANSFER_MTRAN
      ,X2.DAT_TRANSACTION_MTRAN
      ,X2.MSINV_NAM_SUB_INVENTORY_MSIFOR
      ,X2.QTY_PRIMARY_MTRAN
      ,X2.QTY_TRANSACTION_MTRAN
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
 WHERE X2.MTYP_TRANSACTION_TYPE_ID IN (3, 4)
       AND EXISTS
 (SELECT NULL
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X3
         WHERE X3.ID_TRANSFER_MTRAN = X2.MATERIAL_TRANSACTION_ID
               AND X3.QTY_PRIMARY_MTRAN = X2.QTY_PRIMARY_MTRAN
        --
        )
 ORDER BY X2.ITEM_ITEM_ID_FOR
         ,X2.DAT_TRANSACTION_MTRAN
         ,X2.MATERIAL_TRANSACTION_ID
         ,(SELECT ID_TRANSFER_MTRAN
            FROM MAM.MAM_MATERIAL_TRANSACTIONS X3
           WHERE X3.ID_TRANSFER_MTRAN = X2.MATERIAL_TRANSACTION_ID
          --
          )
   FOR UPDATE
