SELECT *
  FROM ( --
        SELECT SUM(X.QTY_PRIMARY_MTRAN) SQ
               ,X.ITEM_ITEM_ID_FOR AS ITEM_ITEM_ID
               ,X.MSLOC_SUB_INVENTORY_LOCATORFOR AS MSLOC_SUB_INVENTORY_LOCATOR_ID
               ,X.MSINV_NAM_SUB_INVENTORY_MSIFOR AS MSINV_NAM_SUB_INVENTORY_MSINV
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X
         WHERE NOT EXISTS (SELECT 1
                  FROM MAM.MAM_SERIAL_NUMBERS S2
                 WHERE S2.ITEM_ITEM_ID = X.ITEM_ITEM_ID_FOR)
         GROUP BY X.ITEM_ITEM_ID_FOR
                  ,X.MSLOC_SUB_INVENTORY_LOCATORFOR
                  ,X.MSINV_NAM_SUB_INVENTORY_MSIFOR
        --
        ) SQ
  FULL OUTER JOIN ( --
                   SELECT QQ.*
                     FROM MAM.MAM_ONHAND_QUANTITIES QQ
                    WHERE NOT EXISTS
                    (SELECT 1
                             FROM MAM.MAM_SERIAL_NUMBERS S1
                            WHERE S1.ITEM_ITEM_ID = QQ.ITEM_ITEM_ID)
                   --
                   ) Q
    ON SQ.ITEM_ITEM_ID = Q.ITEM_ITEM_ID
       AND
       SQ.MSINV_NAM_SUB_INVENTORY_MSINV = Q.MSINV_NAM_SUB_INVENTORY_MSINV
       AND
       SQ.MSLOC_SUB_INVENTORY_LOCATOR_ID = Q.MSLOC_SUB_INVENTORY_LOCATOR_ID
 WHERE Q.QTY_MONH != SQ.SQ
