SELECT SUM(X.QTY_PRIMARY_MTRAN) AS SQ
      ,X.MSINV_NAM_SUB_INVENTORY_MSIFOR
      ,X.MSLOC_SUB_INVENTORY_LOCATORFOR
  FROM MAM.MAM_ITEMS I
 INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
    ON I.ITEM_ID = X.ITEM_ITEM_ID_FOR
 WHERE I.COD_ITEM = &COD_ITEM--7080130009
 GROUP BY X.MSINV_NAM_SUB_INVENTORY_MSIFOR
         ,X.MSLOC_SUB_INVENTORY_LOCATORFOR
