SELECT RX.RCV_TRANSACTION_ID AS RXID
      ,RX.PARENT_TRANSACTION_ID_MRCV AS PARENT_ID
      ,RX.LKP_TYP_TRANSACTION_MRCV
      ,RX.QTY_PRIMARY_MRCV AS QTY
      ,RX.DAT_TRANSACTION_MRCV
      ,TO_CHAR(RX.DAT_TRANSACTION_MRCV
              ,'yyyy/mm/dd hh24:mi:ss'
              ,'nls_calendar=persian') AS SHAMSI
      ,RX.QTY_PRIMARY_MRCV
      ,RX.QTY_PRIMARY_MRCV +
       (SELECT SUM(RX1.QTY_PRIMARY_MRCV)
          FROM MAM.MAM_RCV_TRANSACTIONS RX1
         WHERE RX1.PARENT_TRANSACTION_ID_MRCV = RX.RCV_TRANSACTION_ID
               AND RX1.LKP_TYP_TRANSACTION_MRCV IN ('Correct', 'Return')) AS PURE_QTY
       
      ,RX.*
  FROM MAM.MAM_RCV_TRANSACTIONS RX
 WHERE RX.NUM_RECEIPT_AP_MRCV = TRIM(&NUM_RCV)
 ORDER BY RX.DAT_TRANSACTION_MRCV
         ,RX.RCV_TRANSACTION_ID
