WITH D AS
 ( --
  SELECT --
   X1X.DAT_TRANSACTION_MTRAN AS D
  
    FROM MAM.MAM_MATERIAL_TRANSACTIONS X1X
   WHERE 1 = 1
         AND (X1X.MATERIAL_TRANSACTION_ID IN
         (SELECT MATERIAL_TRANSACTION_ID
                 FROM MAM.MAM_MATERIAL_TRANSACTIONS X0
                WHERE X0.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)
               UNION
               SELECT X2.ID_TRANSFER_MTRAN
                 FROM MAM.MAM_MATERIAL_TRANSACTIONS X2
                WHERE X2.MATERIAL_TRANSACTION_ID IN (&MATERIAL_TRANSACTION_ID)) OR
         X1X.ID_TRANSFER_MTRAN IN (&MATERIAL_TRANSACTION_ID))
  --
  )

SELECT X.MATERIAL_TRANSACTION_ID AS XID
      ,X.ITEM_ITEM_ID_FOR AS I
      ,X.MTYP_TRANSACTION_TYPE_ID AS TT
      ,TO_CHAR(X.DAT_TRANSACTION_MTRAN
              ,'YYYY/MM/DD hh24:mi:ss'
              ,'NLS_CALENDAR=PERSIAN') AS DT
      ,X.QTY_PRIMARY_MTRAN
      ,(SELECT RX.NUM_RECEIPT_AP_MRCV
          FROM MAM.MAM_RCV_TRANSACTIONS RX
         WHERE RX.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID) AS NUM_RECEIPT
      ,X.*
  FROM MAM.MAM_MATERIAL_TRANSACTIONS X

 WHERE 1 = 1
       AND X.DAT_TRANSACTION_MTRAN BETWEEN
       (SELECT D - (10 / 86400) FROM D) AND
       (SELECT D + (10 / 86400) FROM D)
