select * from(
SELECT X.MATERIAL_TRANSACTION_ID
      ,X.DAT_TRANSACTION_MTRAN
      ,TO_CHAR(X.DAT_TRANSACTION_MTRAN) D
      ,X.QTY_TRANSACTION_MTRAN
      ,SUM(X.QTY_TRANSACTION_MTRAN) OVER(PARTITION BY X.ITEM_ITEM_ID_FOR, X.MSINV_NAM_SUB_INVENTORY_MSIFOR ORDER BY X.RN RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LAST_PERIOD

  FROM (SELECT X1.*
              ,ROW_NUMBER() OVER(PARTITION BY X1.ITEM_ITEM_ID_FOR ORDER BY X1.DAT_TRANSACTION_MTRAN, X1.MATERIAL_TRANSACTION_ID) RN
          FROM MAM.MAM_MATERIAL_TRANSACTIONS X1
         WHERE X1.ITEM_ITEM_ID_FOR =
               (SELECT I.ITEM_ID
                  FROM MAM.MAM_ITEMS I
                 WHERE I.COD_ITEM = &COD_ITEM)
               AND X1.MSINV_NAM_SUB_INVENTORY_MSIFOR = &MSINV_NAM_SUB_INVENTORY_MSIFOR) X
)-- where last_period<0
ORDER BY DAT_TRANSACTION_MTRAN
