SELECT O.ORDER_ID
      ,O.NUM_PGV_PUROR
      ,O.NUM_MDF_PUROR
      ,O.NUM_SPFC_PUROR
      ,OP.NUM_POS_PUROP
      ,R.LKP_TYP_REQ_PURRQ
      ,I.COD_ITEM
      ,I.DES_ITEM
      ,I.LKP_ROUTING_RECEIPT_ITEM
      ,RX.NUM_RECEIPT_AP_MRCV
      ,RX.RCV_TRANSACTION_ID
      ,RX.LKP_TYP_TRANSACTION_MRCV
      ,RX.ORPYDORPYM_NUM_ORD_PYM_ORPYM
      ,RX.SPINV_NUM_SRL_SPINV
  FROM PUR.PUR_ORDERS O
 INNER JOIN PUR.PUR_ORDER_POSITIONS OP
    ON O.ORDER_ID = OP.PUROR_ORDER_ID
 INNER JOIN PUR.PUR_REQUEST_POSITIONS RP
    ON OP.PURRP_PURRP_ID = RP.PURRP_ID
 INNER JOIN PUR.PUR_REQUESTS R
    ON RP.PURRQ_NUM_PGV_PURRQ = R.NUM_PGV_PURRQ
 INNER JOIN MAM.MAM_ITEMS I
    ON RP.ITEM_ITEM_ID = I.ITEM_ID
  LEFT OUTER JOIN (SELECT *
                     FROM MAM.MAM_RCV_TRANSACTIONS RX1
                    WHERE RX1.NUM_RECEIPT_AP_MRCV = &NUM_RECEIPT_AP_MRCV
                          OR &NUM_RECEIPT_AP_MRCV IS NULL) RX
    ON OP.PUROP_ID = RX.PUROP_PUROP_ID
 WHERE 1 = 1 --
       AND O.NUM_PGV_PUROR = TRIM(&NUM_PGV_PUROR)
--       AND OP.PUROP_ID = TRIM(&PUROP_ID)
 ORDER BY O.ORDER_ID
         ,O.NUM_SPFC_PUROR
         ,RX.NUM_RECEIPT_AP_MRCV
         ,I.COD_ITEM
         ,RX.RCV_TRANSACTION_ID
