SELECT DISTINCT I.*
  FROM MAM.MAM_ITEMS I
 WHERE I.MUOM_MEASUREMENT_UNIT_ID = 2
       AND I.COD_ITEM NOT LIKE '5%';
SELECT DISTINCT O.NUM_PGV_PUROR, I.*
  FROM PUR.PUR_ORDERS O
 INNER JOIN PUR.PUR_ORDER_POSITIONS OP
    ON O.ORDER_ID = OP.PUROR_ORDER_ID
 INNER JOIN PUR.PUR_REQUEST_POSITIONS RP
    ON OP.PURRP_PURRP_ID = RP.PURRP_ID
 INNER JOIN MAM.MAM_ITEMS I
    ON RP.ITEM_ITEM_ID = I.ITEM_ID
 WHERE I.MUOM_MEASUREMENT_UNIT_ID = 2
       AND I.COD_ITEM NOT LIKE '5%';
