SELECT D.MRCXN_RCV_CONTRACT_X_NSPCT_ID
      ,D.RCV_CONTRACT_X_DLVR_ID
      ,D.MRCXD_RCV_CONTRACT_X_DLVR_ID
      ,D.NUM_QTY_MRCXD
      ,D.MTRAN_MATERIAL_TRANSACTION_ID
      ,X.QTY_PRIMARY_MTRAN
      ,X.MTYP_TRANSACTION_TYPE_ID AS TT
       --      ,X.ORPYD_ORPYM_NUM_ORD_PYM_ORPYM
       --      ,X.SPINV_NUM_SRL_SPINV
      ,TO_CHAR(X.DAT_TRANSACTION_MTRAN
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DH
      ,X2.MATERIAL_TRANSACTION_ID
      ,X2.MTYP_TRANSACTION_TYPE_ID
      ,TO_CHAR(X2.DAT_TRANSACTION_MTRAN
              ,'YYYY/MM/DD HH24:MI:SS'
              ,'NLS_CALENDAR=PERSIAN') AS DH2
--      ,D.*
  FROM MAM.MAM_RCV_CONTRACT_X_DLVRS D
  LEFT OUTER JOIN MAM.MAM_RCV_CONTRACT_X_DLVRS D2
    ON D2.MRCXD_RCV_CONTRACT_X_DLVR_ID = D.RCV_CONTRACT_X_DLVR_ID
  LEFT OUTER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X2
    ON D2.MTRAN_MATERIAL_TRANSACTION_ID = X2.MATERIAL_TRANSACTION_ID
 INNER JOIN MAM.MAM_MATERIAL_TRANSACTIONS X
    ON D.MTRAN_MATERIAL_TRANSACTION_ID = X.MATERIAL_TRANSACTION_ID
 WHERE D.MRCXN_RCV_CONTRACT_X_NSPCT_ID IN ( --
                                           SELECT R.MRCXN_RCV_CONTRACT_X_NSPCT_ID
                                             FROM MAM.MAM_RCV_CONTRACT_X_DLVRS R
                                            GROUP BY R.MRCXN_RCV_CONTRACT_X_NSPCT_ID
                                           HAVING COUNT(R.MTRAN_MATERIAL_TRANSACTION_ID) > 1
                                           --
                                           )
       AND D.MRCXN_RCV_CONTRACT_X_NSPCT_ID = 8824
 ORDER BY D.MRCXN_RCV_CONTRACT_X_NSPCT_ID
         ,D.RCV_CONTRACT_X_DLVR_ID
